// Arayüz metinleri — 4 dil (TR · EN · AR · FA). AR ve FA sağdan sola (RTL) gösterilir.
// Türkçe sözlük kaynak kabul edilir; diğer diller aynı anahtarların tamamını içermek zorundadır.
import type { Dil } from "./types";

const tr = {

  "nav.ustalar": "Ustalar",
  "nav.cagri": "Çağrı",
  "nav.isEmirleri": "İş Emirlerim",
  "nav.profil": "Profil",

  "tema.degistir": "Tema: {ad} (değiştirmek için dokunun)",
  "tema.sistem": "Sistem",
  "tema.gunduz": "Gündüz",
  "tema.gece": "Gece",
  "genel.kapat": "Kapat",
  "durum.yukleniyor": "Yükleniyor…",
  "durum.hataBaslik": "Bir şeyler ters gitti",
  "durum.tekrarDene": "Tekrar dene",
  "durum.ustalarHata": "Usta listesi yüklenemedi. Biraz sonra tekrar deneyin.",
  "durum.isEmirleriHata": "İş emirleriniz okunamadı. Tekrar deneyin; sorun sürerse uygulamayı yeniden açın.",
  "durum.ustaYokBaslik": "Bu bölgede henüz usta yok",
  "durum.ustaYokMetin": "Yakında yeni ustalar eklenecek. Başka bir semt seçerek de arayabilirsiniz.",
  "durum.suzgecBosMetin": "Arama kelimesini ya da süzgeçleri değiştirin.",
  "durum.aktifYokMetin": "Bir usta çağırdığınızda canlı takibi burada görürsünüz.",
  "durum.gecmisYokMetin": "Tamamlanan ve iptal edilen işler burada listelenir.",
  "dil.sec": "Dil seçin",

  "kategori.tesisat": "Tesisat",
  "kategori.elektrik": "Elektrik",
  "kategori.cilingir": "Çilingir",
  "kategori.kombi": "Kombi",
  "kategori.beyaz-esya": "Beyaz Eşya",

  "sorun.su-sizintisi": "Su sızıntısı",
  "sorun.tikali-gider": "Tıkalı gider",
  "sorun.musluk-ariza": "Musluk arızası",
  "sorun.sigorta-atiyor": "Sigorta sürekli atıyor",
  "sorun.priz-yanik": "Priz yanık kokuyor",
  "sorun.elektrik-yok": "Evde elektrik yok",
  "sorun.kapida-kaldim": "Kapıda kaldım",
  "sorun.kilit-degisimi": "Kilit değişimi",
  "sorun.anahtar-kirildi": "Anahtar kilitte kırıldı",
  "sorun.sicak-su-yok": "Sıcak su yok",
  "sorun.basinc-dusuk": "Kombi basınç düşürüyor",
  "sorun.petek-isinmiyor": "Petekler ısınmıyor",
  "sorun.camasir-makinesi": "Çamaşır makinesi su boşaltmıyor",
  "sorun.buzdolabi": "Buzdolabı soğutmuyor",
  "sorun.bulasik-makinesi": "Bulaşık makinesi çalışmıyor",

  "aciliyet.hemen": "Hemen",
  "aciliyet.bugun": "Bugün",
  "aciliyet.randevu": "Randevu",

  "liste.baslik": "Yakınındaki ustalar",
  "liste.arama": "Usta adı, uzmanlık veya semt ara",
  "liste.tumu": "Tümü",
  "liste.sadeceMusait": "Sadece müsait olanlar",
  "liste.sonuc": "{n} usta",
  "liste.bos": "Aramanıza uygun usta bulunamadı.",

  "kart.musait": "Şu an müsait",
  "kart.mesgul": "Meşgul",
  "kart.km": "{n} km",
  "kart.yorum": "{n} yorum",
  "kart.cikis": "Çıkış ücreti {tutar}",

  "detay.deneyim": "Deneyim",
  "detay.yil": "{n} yıl",
  "detay.tamamlanan": "Tamamlanan iş",
  "detay.sorunSec": "Sorununuz ne?",
  "detay.aciliyet": "Ne zaman gelsin?",
  "detay.saat": "Ziyaret saati",
  "detay.tarih": "Tarih",
  "detay.acilUcret": "+{tutar} acil servis ücreti",
  "detay.bugunSaatYok": "Bugün için boş saat kalmadı, lütfen randevu seçin.",
  "detay.adres": "Adres notu",
  "detay.adresOrnek": "Kat, daire no, zil adı…",
  "detay.ustayaIletilen": "Ustaya Türkçe iletilecek:",
  "detay.mesgulUyari": "Bu usta şu an meşgul; yalnızca randevu alabilirsiniz.",
  "detay.cagirKisa": "Ustayı çağır",

  "cagri.baslik": "Çağrı özeti",
  "cagri.bos": "Henüz bir çağrı oluşturmadınız.",
  "cagri.ustaSec": "Bir usta seçin →",
  "cagri.sorun": "Sorun",
  "cagri.zaman": "Zaman",
  "cagri.adres": "Adres notu",
  "cagri.cikis": "Çıkış ücreti",
  "cagri.acil": "Acil servis ücreti",
  "cagri.toplam": "Tahmini toplam",
  "cagri.gece": "Gece ek ücreti (22:00–08:00)",
  "cagri.pazar": "Pazar ek ücreti",
  "cagri.iscilik": "Tahmini işçilik",
  "cagri.not": "Parça ve işçilik ücreti usta tarafından yerinde belirlenir.",
  "cagri.onayla": "Çağrıyı onayla",
  "cagri.isleniyor": "İş emri kodu üretiliyor…",
  "cagri.vazgec": "Vazgeç",
  "cagri.hata": "Kod üretilemedi:",

  "is.baslik": "İş Emirlerim",
  "is.kod": "İş emri kodu",
  "is.kodNot": "Usta kapıya geldiğinde bu kodu söylemesini isteyin.",
  "is.iptal": "İptal et",
  "is.dogrulaBaslik": "Kapıdaki ustayı doğrula",
  "is.dogrulaYer": "Ustanın söylediği kod",
  "is.dogrulaBtn": "Doğrula",
  "is.yanlis": "Bu kod iş emirlerinizde yok. Kapıyı açmayın!",
  "is.formatHatali": "Kod biçimi hatalı (ör. UST-ELK-1210-K7QZ).",
  "is.kontrolHatali": "Kod yanlış yazılmış olabilir: kontrol karakteri tutmuyor. Ustadan kodu tekrar söylemesini isteyin.",

  "durum.tamamlandi": "Tamamlandı",
  "durum.iptal": "İptal edildi",

  "profil.misafir": "Misafir kullanıcı",
  "profil.ad": "Ad Soyad",
  "profil.telefon": "Telefon",
  "profil.adres": "Adres",
  "profil.kaydet": "Kaydet",
  "profil.kaydedildi": "Kaydedildi ✓",
  "profil.ayarlar": "Ayarlar",
  "profil.dil": "Uygulama dili",
  "profil.tema": "Tema",
  "profil.bilgi": "Bilgi ve yasal",

  "sayfa.hakkinda": "Hakkında",
  "sayfa.iletisim": "İletişim",
  "sayfa.kosullar": "Kullanım Koşulları",
  "sayfa.gizlilik": "Gizlilik Politikası",

  "iletisim.aciklama": "Soru, öneri veya usta başvurusu için bize yazın. Genellikle 1 iş günü içinde yanıt veririz.",
  "iletisim.ad": "Adınız",
  "iletisim.eposta": "E-posta",
  "iletisim.konu": "Konu",
  "iletisim.mesaj": "Mesajınız",
  "iletisim.ipucu": "Tüm alanları doldurun; mesaj en az 10 karakter olmalı.",
  "iletisim.gonder": "Gönder",
  "iletisim.gonderiliyor": "Gönderiliyor…",
  "iletisim.basarili": "Mesajınız iletildi. Teşekkür ederiz!",
  "konu.genel": "Genel soru",
  "konu.usta": "Usta olarak katılmak istiyorum",
  "konu.sikayet": "Şikayet",
  "konu.oneri": "Öneri",

  "liste.merhaba": "Merhaba",
  "liste.merhabaAd": "Merhaba, {ad}",
  "liste.soru": "Ne tamir edelim?",
  "liste.konumSec": "Semtinizi seçin",
  "liste.acilBaslik": "Acil mi? En yakın müsait usta",
  "liste.acilYok": "Şu an müsait usta yok",
  "liste.aktifYolda": "{usta} yolda · yaklaşık {dk} dk",
  "liste.aktifRandevu": "{usta} · randevu {zaman}",
  "liste.favoriler": "Favoriler",
  "liste.dilimiKonusan": "Türkçe konuşan",
  "liste.sirala": "Sırala",
  "liste.gorunum": "Görünüm",
  "liste.liste": "Liste",
  "liste.harita": "Harita",
  "liste.filtreTemizle": "Filtreleri temizle",
  "sirala.onerilen": "Önerilen",
  "sirala.yakin": "En yakın",
  "sirala.puan": "En yüksek puan",
  "sirala.fiyat": "En uygun fiyat",

  "kart.kapali": "Kapalı · {saat} açılır",
  "kart.dk": "~{dk} dk",
  "kart.favoriEkle": "Favorilere ekle",
  "kart.favoriCikar": "Favorilerden çıkar",
  "kart.favoriEklendi": "{ad} favorilere eklendi",
  "kart.favoriCikarildi": "{ad} favorilerden çıkarıldı",

  "rozet.dogrulanmis": "Kimliği doğrulandı",
  "rozet.sigortali": "Sigortalı işçilik",
  "rozet.7-24": "7/24 hizmet",
  "rozet.hizli-yanit": "Hızlı yanıt",

  "detay.geri": "Geri",
  "detay.yanit": "Yanıt süresi",
  "detay.mesafe": "Uzaklık",
  "detay.calisma": "Çalışma saatleri",
  "detay.724": "7 gün 24 saat",
  "detay.diller": "Konuştuğu diller",
  "detay.dilinizi": "Sizin dilinizi konuşuyor",
  "detay.sure": "~{dk} dk iş",
  "detay.guvenlik": "Usta gelene kadar",
  "detay.foto": "Arızanın fotoğrafını ekleyin (isteğe bağlı)",
  "detay.fotoNot": "Fotoğraf, ustanın doğru parçayla gelmesine yardım eder.",
  "detay.fotoKaldir": "Fotoğrafı kaldır",
  "detay.yorumlar": "Yorumlar",
  "detay.yorumSayisi": "{n} değerlendirme",
  "detay.tumYorumlar": "Tüm yorumları göster",
  "detay.sizinYorumunuz": "Sizin yorumunuz",
  "detay.kapaliUyari": "Bu usta şu an kapalı ({saat} açılır); bugün daha sonrası veya randevu seçebilirsiniz.",

  "ipucu.su-sizintisi": "Ana su vanasını kapatın; sızan suyu prizlerden ve elektrikli cihazlardan uzak tutun.",
  "ipucu.tikali-gider": "Kimyasal açıcı dökmeyin; usta gelene kadar o gideri kullanmayın.",
  "ipucu.musluk-ariza": "Lavabonun altındaki ara musluğu kapatın.",
  "ipucu.sigorta-atiyor": "Son taktığınız cihazı prizden çekin; sigortayı tekrar tekrar kaldırmayın.",
  "ipucu.priz-yanik": "O hattın sigortasını kapatın, prize dokunmayın. Duman veya alev varsa 112'yi arayın.",
  "ipucu.elektrik-yok": "Komşularda da elektrik yoksa genel kesinti olabilir; buzdolabının kapağını açmayın.",
  "ipucu.kapida-kaldim": "Kapıyı zorlamayın; kimliğinizi yanınızda bulundurun, usta ev sahipliğini soracaktır.",
  "ipucu.kilit-degisimi": "Kullandığınız kilit tipinin fotoğrafını ekleyin; usta uygun silindiri getirsin.",
  "ipucu.anahtar-kirildi": "Kırık parçayı kendiniz çıkarmaya çalışmayın; kilit daha çok zarar görebilir.",
  "ipucu.sicak-su-yok": "Kombinin ekranındaki hata kodunu not edin ve kombiyi kapatıp açmayı bir kez deneyin.",
  "ipucu.basinc-dusuk": "Basınç göstergesinin fotoğrafını çekin; kombiyi kapatın.",
  "ipucu.petek-isinmiyor": "Peteklerin vanalarının açık olduğundan emin olun.",
  "ipucu.camasir-makinesi": "Makineyi kapatıp fişini çekin; kapağı zorlamayın.",
  "ipucu.buzdolabi": "Kapağı olabildiğince kapalı tutun; bozulabilecek gıdaları serin bir yere alın.",
  "ipucu.bulasik-makinesi": "Makinenin fişini çekin ve su musluğunu kapatın.",

  "harita.etiket": "İstanbul'daki ustaların haritası",
  "harita.sen": "Siz",
  "harita.profil": "Profili gör",
  "harita.avrupa": "Avrupa Yakası",
  "harita.asya": "Anadolu Yakası",

  "karsilama.baslik": "Ustam'a hoş geldiniz",
  "karsilama.slogan": "Arıza senden, usta bizden.",
  "karsilama.alt": "Evdeki arızaya en yakın müsait ustayı, kendi dilinizde çağırın.",
  "karsilama.dilSec": "Dilinizi seçin",
  "karsilama.semtSec": "Hangi semttesiniz?",
  "karsilama.semtNot": "En yakın ustaları göstermek için kullanılır; cihazınızdan çıkmaz.",
  "karsilama.devam": "Devam",
  "karsilama.basla": "Başla",

  "genel.vazgec": "Vazgeç",

  "cagri.iletisim": "İletişim telefonu",
  "cagri.telefonNot": "Usta yola çıkınca sizi bu numaradan arar; numara profilinize kaydedilir.",
  "cagri.telefonHata": "Geçerli bir telefon numarası girin.",
  "cagri.odeme": "Ödeme tercihi",
  "odeme.nakit": "Kapıda nakit",
  "odeme.kart": "Kapıda kart",
  "cagri.odemeNot": "Uygulama ödeme almaz; ödeme iş bitince ustaya yapılır.",
  "cagri.kosullarOnay": "Kullanım koşullarını okudum, kabul ediyorum.",
  "cagri.motorRust": "Hesaplama: Rust çekirdeği",
  "cagri.motorTs": "Hesaplama: tarayıcı (TypeScript)",
  "cagri.olusturuldu": "İş emri oluşturuldu: {kod}",

  "is.aktif": "Aktif",
  "is.gecmis": "Geçmiş",
  "is.aktifYok": "Aktif bir çağrınız yok.",
  "is.gecmisYok": "Geçmiş iş emriniz yok.",
  "asama.alindi": "Talep alındı",
  "asama.onaylandi": "Usta onayladı",
  "asama.yolda": "Yolda",
  "asama.kapida": "Kapıda",
  "asama.tamamlandi": "Tamamlandı",
  "is.varis": "Tahmini varış {saat}",
  "is.kalan": "{dk} dk kaldı",
  "is.randevu": "Randevu: {zaman}",
  "is.kapidaNot": "Usta kapıda olmalı. Kapıyı açmadan önce söylediği kodu doğrulayın.",
  "is.kopyala": "Kodu kopyala",
  "is.kopyalandi": "Kod kopyalandı",
  "is.qrGoster": "QR kodu göster",
  "is.qrGizle": "QR kodu gizle",
  "is.qrEtiket": "{kod} iş emri kodunun QR karşılığı",
  "is.qrNot": "Usta bu QR'ı okutarak işi kendi kaydına geçirir.",
  "is.fiyatDokumu": "Fiyat dökümü",
  "is.dogrulandi": "Usta doğrulandı",
  "is.bitir": "İş tamamlandı",
  "is.bitirNot": "İşi tamamlamak için önce kapıdaki ustanın kodunu doğrulayın.",
  "is.iptalBaslik": "Çağrıyı iptal et",
  "is.iptalSoru": "İptal nedeniniz nedir?",
  "iptal.vazgectim": "Vazgeçtim",
  "iptal.gecikti": "Usta gecikti",
  "iptal.baskasi": "Başka bir usta buldum",
  "iptal.cozuldu": "Sorun kendiliğinden çözüldü",
  "is.iptalOnay": "Çağrıyı iptal et",
  "is.iptalEdildi": "Çağrı iptal edildi",
  "is.degerlendir": "Değerlendir",
  "is.degerlendirBaslik": "{usta} nasıldı?",
  "is.yorumYer": "Deneyiminizi birkaç cümleyle anlatın (isteğe bağlı)",
  "is.gonder": "Gönder",
  "is.tesekkur": "Değerlendirmeniz için teşekkürler!",
  "is.puaniniz": "Puanınız",
  "is.puanSec": "{n} yıldız",
  "is.tekrar": "Tekrar çağır",
  "is.odeme": "Ödeme",
  "is.ustaArayacak": "Usta sizi {telefon} numarasından arayacak.",

  "profil.toplamIs": "Toplam iş",
  "profil.tamamlananIs": "Tamamlanan",
  "profil.harcama": "Harcama",
  "profil.yorumlarim": "Yorumlarım",
  "profil.favoriUstalar": "Favori ustalarım",
  "profil.favoriYok": "Henüz favori ustanız yok. Usta kartındaki kalbe dokunun.",
  "profil.veri": "Verilerim (KVKK)",
  "profil.disaAktar": "Verilerimi dışa aktar (JSON)",
  "profil.sil": "Bu cihazdaki tüm verilerimi sil",
  "profil.silBaslik": "Tüm veriler silinsin mi?",
  "profil.silNot": "Profiliniz, iş emirleriniz, favorileriniz ve yorumlarınız bu cihazdan kalıcı olarak silinir. Bu, KVKK kapsamındaki silme hakkınızdır.",
  "profil.silOnay": "Evet, hepsini sil",
  "profil.silindi": "Tüm verileriniz silindi.",
  "profil.surum": "Sürüm {surum} · Çekirdek: {motor}",
  "motor.rust": "Rust (Tauri)",
  "motor.ts": "Tarayıcı (TypeScript)",

  "karsilama.atla": "Atla",
  "karsilama.ileri": "İleri",
  "karsilama.adim1Baslik": "Arızanı seç",
  "karsilama.adim1Metin": "Su kaçağı, elektrik, kilit, kombi… Ne olduğunu iki dokunuşla anlat.",
  "karsilama.adim2Baslik": "Yakınındaki müsait ustayı bul",
  "karsilama.adim2Metin": "Mesafeyi, varış süresini, puanı ve fiyat aralığını çağırmadan önce gör.",
  "karsilama.adim3Baslik": "İş emrini güvenle takip et",
  "karsilama.adim3Metin": "Kapıdaki ustanın kodunu doğrula; kod tutmazsa kapıyı açma.",
  "karsilama.adim": "Adım {n} / {toplam}",
  "genel.cevrimdisi": "Çevrimdışısınız. Verileriniz bu cihazda olduğu için uygulama çalışmaya devam eder.",

  "liste.konumDegistir": "Konumu değiştir: {semt}",
  "liste.neOldu": "Ne oldu?",
  "liste.acilAlt": "En yakın müsait usta, tek dokunuşla",
  "liste.enYakin": "{usta} · ~{dk} dk",
  "liste.tarifEt": "Arızayı adım adım tarif et",
  "liste.aramaOneri": "Sorunlar",
  "liste.tumUstalar": "Tüm ustalar",
  "liste.filtrele": "Filtrele",
  "liste.siralaEtiket": "Sırala: {ad}",
  "filtre.baslik": "Filtreler",
  "filtre.durum": "Durum",
  "filtre.mesafe": "Mesafe",
  "filtre.mesafeKm": "≤ {n} km",
  "filtre.puan": "En az puan",
  "filtre.fiyat": "Çıkış ücreti",
  "filtre.fiyatEnFazla": "≤ {tutar}",
  "filtre.dil": "Konuştuğu dil",
  "filtre.tumu": "Tümü",
  "filtre.temizle": "Temizle",
  "filtre.goster": "{n} ustayı göster",
  "sirala.baslik": "Sıralama",
  "sirala.onerilenAciklama": "Müsaitlik, mesafe, puan, yanıt süresi ve dil birlikte",
  "sirala.yakinAciklama": "Size en yakın olan önce",
  "sirala.puanAciklama": "Ortalama puanı en yüksek olan önce",
  "sirala.fiyatAciklama": "Çıkış ücreti en düşük olan önce",
  "neden.ac": "Neden önerildi?",
  "neden.baslik": "Bu ustayı neden öneriyoruz?",
  "neden.musait": "Şu an müsait ve hemen gelebilir",
  "neden.yakin": "Size {km} km uzaklıkta",
  "neden.puan": "{puan} ortalama puan",
  "neden.hizli": "Ortalama {dk} dk'da yanıt veriyor",
  "neden.dil": "{dil} konuşuyor",
  "neden.fiyat": "Çıkış ücreti ortalamanın altında",
  "neden.not": "Sıralama yalnızca bu bilgilerle, sabit kurallarla yapılır; ücretli öne çıkarma yoktur.",
  "kart.simdiGelebilir": "Şimdi gelebilir · ~{dk} dk",
  "kart.mesgulSonra": "Meşgul · ~{dk} dk sonra müsait",
  "kart.cikisDan": "Çıkış {tutar}",
  "sihirbaz.alanSoru": "Sorun hangi alanda?",
  "sihirbaz.sorunSoru": "Hangisi en yakın?",
  "sihirbaz.aciliyetSoru": "Ne kadar acil?",
  "sihirbaz.hemen": "Şu an devam ediyor, hemen gelmeli",
  "sihirbaz.bugun": "Bugün içinde gelsin",
  "sihirbaz.randevu": "Acil değil, randevu yeterli",
  "sihirbaz.sonuc": "Size uygun ustalar",
  "sihirbaz.sonucYok": "Şu an bu koşullara uyan usta yok. Randevu seçeneğini deneyin.",
  "sihirbaz.sec": "Bu ustayı seç",
  "harita.listeyeDon": "Listeye dön",

  "detay.hemenVaris": "Usta yaklaşık {dk} dk içinde kapınızda olabilir.",
  "detay.acilAra": "Duman, alev ya da yaralanma varsa önce 112'yi arayın",
  "detay.fotoGizlilik": "Fotoğraf yalnızca bu cihazda kalır ve küçültülerek kaydedilir; hiçbir sunucuya gönderilmez.",
  "detay.fotoHata": "Bu dosya kullanılamıyor. 15 MB'tan küçük bir fotoğraf seçin.",
  "detay.fotoSec": "Fotoğraf çek ya da seç",
  "detay.varis": "Varış",
  "detay.yarin": "Yarın",
  "cagri.adimUsta": "Usta",
  "cagri.adimOnay": "Onay",
  "cagri.degistir": "Değiştir",
  "cagri.tekrarDene": "Tekrar dene",
  "fiyat.nasil": "Nasıl hesaplandı?",
  "fiyat.kuralCikis": "Çıkış ücreti ustanın sabit ücretidir.",
  "fiyat.kuralAcil": "\"Hemen\" çağrılarında {tutar} acil servis ücreti eklenir.",
  "fiyat.kuralGece": "Ziyaret 22:00–08:00 arasındaysa çıkış ücretinin %25'i eklenir.",
  "fiyat.kuralPazar": "Ziyaret Pazar günüyse çıkış ücretinin %15'i eklenir.",
  "fiyat.kuralIscilik": "İşçilik sorun tipine göre tahmini bir aralıktır; kesin tutarı usta yerinde söyler.",

  "is.guvenlikKodu": "Güvenlik kodu",
  "is.yanlisBaslik": "Kapıyı açmayın",
  "is.yanlisMetin": "Bu kod sizin iş emrinize ait değil. Ustadan kodu tekrar söylemesini isteyin; şüpheniz sürerse 112'yi arayın.",
  "is.dogruBaslik": "Kod doğru",
  "is.dogruMetin": "Bu, sizin çağırdığınız usta. Kapıyı açabilirsiniz.",
  "is.ustaBilgi": "{kategori} · {semt}",
  "profil.hesabim": "Hesabım",
  "profil.konum": "Konum",
  "profil.gorunum": "Görünüm",
  "profil.gizlilik": "Gizlilik",
  "profil.verilenPuan": "Verdiğin puan",
  "profil.favoriBosBaslik": "Henüz favori ustan yok",
  "profil.favoriBosMetin": "Beğendiğin ustaları kaydet; bir sonraki arızada daha hızlı ulaş.",
  "profil.ustalaraGoz": "Ustalara göz at",
} as const;

export type Anahtar = keyof typeof tr;

const en: Record<Anahtar, string> = {

  "nav.ustalar": "Pros",
  "nav.cagri": "Request",
  "nav.isEmirleri": "My Jobs",
  "nav.profil": "Profile",

  "tema.degistir": "Theme: {ad} (tap to change)",
  "tema.sistem": "System",
  "tema.gunduz": "Light",
  "tema.gece": "Dark",
  "genel.kapat": "Close",
  "durum.yukleniyor": "Loading…",
  "durum.hataBaslik": "Something went wrong",
  "durum.tekrarDene": "Try again",
  "durum.ustalarHata": "The list of pros could not be loaded. Please try again in a moment.",
  "durum.isEmirleriHata": "Your jobs could not be read. Try again; if it keeps happening, reopen the app.",
  "durum.ustaYokBaslik": "No pros in this area yet",
  "durum.ustaYokMetin": "New pros are joining soon. You can also search by choosing another district.",
  "durum.suzgecBosMetin": "Change your search words or filters.",
  "durum.aktifYokMetin": "When you call a pro, you will follow the job live here.",
  "durum.gecmisYokMetin": "Completed and cancelled jobs are listed here.",
  "dil.sec": "Choose language",

  "kategori.tesisat": "Plumbing",
  "kategori.elektrik": "Electrical",
  "kategori.cilingir": "Locksmith",
  "kategori.kombi": "Boiler",
  "kategori.beyaz-esya": "Appliances",

  "sorun.su-sizintisi": "Water leak",
  "sorun.tikali-gider": "Clogged drain",
  "sorun.musluk-ariza": "Broken faucet",
  "sorun.sigorta-atiyor": "Fuse keeps tripping",
  "sorun.priz-yanik": "Outlet smells burnt",
  "sorun.elektrik-yok": "No power at home",
  "sorun.kapida-kaldim": "Locked out",
  "sorun.kilit-degisimi": "Lock replacement",
  "sorun.anahtar-kirildi": "Key broke in the lock",
  "sorun.sicak-su-yok": "No hot water",
  "sorun.basinc-dusuk": "Boiler losing pressure",
  "sorun.petek-isinmiyor": "Radiators not heating",
  "sorun.camasir-makinesi": "Washing machine won't drain",
  "sorun.buzdolabi": "Fridge not cooling",
  "sorun.bulasik-makinesi": "Dishwasher not working",

  "aciliyet.hemen": "Right now",
  "aciliyet.bugun": "Today",
  "aciliyet.randevu": "Schedule",

  "liste.baslik": "Pros near you",
  "liste.arama": "Search name, trade or district",
  "liste.tumu": "All",
  "liste.sadeceMusait": "Available only",
  "liste.sonuc": "{n} pros",
  "liste.bos": "No pros match your search.",

  "kart.musait": "Available now",
  "kart.mesgul": "Busy",
  "kart.km": "{n} km",
  "kart.yorum": "{n} reviews",
  "kart.cikis": "Call-out fee {tutar}",

  "detay.deneyim": "Experience",
  "detay.yil": "{n} yrs",
  "detay.tamamlanan": "Jobs done",
  "detay.sorunSec": "What's the problem?",
  "detay.aciliyet": "When should they come?",
  "detay.saat": "Visit time",
  "detay.tarih": "Date",
  "detay.acilUcret": "+{tutar} emergency fee",
  "detay.bugunSaatYok": "No slots left today, please schedule a visit.",
  "detay.adres": "Address note",
  "detay.adresOrnek": "Floor, flat no, doorbell name…",
  "detay.ustayaIletilen": "Sent to the pro in Turkish:",
  "detay.mesgulUyari": "This pro is busy right now; you can only schedule a visit.",
  "detay.cagirKisa": "Call the pro",

  "cagri.baslik": "Request summary",
  "cagri.bos": "You haven't created a request yet.",
  "cagri.ustaSec": "Choose a pro →",
  "cagri.sorun": "Problem",
  "cagri.zaman": "Time",
  "cagri.adres": "Address note",
  "cagri.cikis": "Call-out fee",
  "cagri.acil": "Emergency fee",
  "cagri.toplam": "Estimated total",
  "cagri.gece": "Night surcharge (22:00–08:00)",
  "cagri.pazar": "Sunday surcharge",
  "cagri.iscilik": "Estimated labour",
  "cagri.not": "Parts and labour are priced on site by the pro.",
  "cagri.onayla": "Confirm request",
  "cagri.isleniyor": "Generating job code…",
  "cagri.vazgec": "Cancel",
  "cagri.hata": "Could not generate code:",

  "is.baslik": "My Jobs",
  "is.kod": "Job code",
  "is.kodNot": "Ask the pro to tell you this code at the door.",
  "is.iptal": "Cancel",
  "is.dogrulaBaslik": "Verify the pro at your door",
  "is.dogrulaYer": "Code the pro tells you",
  "is.dogrulaBtn": "Verify",
  "is.yanlis": "This code is not in your jobs. Do not open the door!",
  "is.formatHatali": "Invalid code format (e.g. UST-ELK-1210-K7QZ).",
  "is.kontrolHatali": "The code may be mistyped: the check character does not match. Ask the pro to repeat it.",

  "durum.tamamlandi": "Done",
  "durum.iptal": "Cancelled",

  "profil.misafir": "Guest user",
  "profil.ad": "Full name",
  "profil.telefon": "Phone",
  "profil.adres": "Address",
  "profil.kaydet": "Save",
  "profil.kaydedildi": "Saved ✓",
  "profil.ayarlar": "Settings",
  "profil.dil": "App language",
  "profil.tema": "Theme",
  "profil.bilgi": "Info & legal",

  "sayfa.hakkinda": "About",
  "sayfa.iletisim": "Contact",
  "sayfa.kosullar": "Terms of Use",
  "sayfa.gizlilik": "Privacy Policy",

  "iletisim.aciklama": "Write to us with questions, ideas or to join as a pro. We usually reply within 1 business day.",
  "iletisim.ad": "Your name",
  "iletisim.eposta": "Email",
  "iletisim.konu": "Subject",
  "iletisim.mesaj": "Your message",
  "iletisim.ipucu": "Fill in all fields; the message must be at least 10 characters.",
  "iletisim.gonder": "Send",
  "iletisim.gonderiliyor": "Sending…",
  "iletisim.basarili": "Your message has been sent. Thank you!",
  "konu.genel": "General question",
  "konu.usta": "I want to join as a pro",
  "konu.sikayet": "Complaint",
  "konu.oneri": "Suggestion",

  "liste.merhaba": "Hello",
  "liste.merhabaAd": "Hello, {ad}",
  "liste.soru": "What needs fixing?",
  "liste.konumSec": "Choose your district",
  "liste.acilBaslik": "Urgent? Nearest available pro",
  "liste.acilYok": "No pro available right now",
  "liste.aktifYolda": "{usta} is on the way · about {dk} min",
  "liste.aktifRandevu": "{usta} · appointment {zaman}",
  "liste.favoriler": "Favourites",
  "liste.dilimiKonusan": "Speaks English",
  "liste.sirala": "Sort",
  "liste.gorunum": "View",
  "liste.liste": "List",
  "liste.harita": "Map",
  "liste.filtreTemizle": "Clear filters",
  "sirala.onerilen": "Recommended",
  "sirala.yakin": "Nearest",
  "sirala.puan": "Top rated",
  "sirala.fiyat": "Lowest price",

  "kart.kapali": "Closed · opens {saat}",
  "kart.dk": "~{dk} min",
  "kart.favoriEkle": "Add to favourites",
  "kart.favoriCikar": "Remove from favourites",
  "kart.favoriEklendi": "{ad} added to favourites",
  "kart.favoriCikarildi": "{ad} removed from favourites",

  "rozet.dogrulanmis": "ID verified",
  "rozet.sigortali": "Insured work",
  "rozet.7-24": "24/7 service",
  "rozet.hizli-yanit": "Fast response",

  "detay.geri": "Back",
  "detay.yanit": "Response time",
  "detay.mesafe": "Distance",
  "detay.calisma": "Working hours",
  "detay.724": "24 hours, 7 days",
  "detay.diller": "Languages spoken",
  "detay.dilinizi": "Speaks your language",
  "detay.sure": "~{dk} min job",
  "detay.guvenlik": "Until the pro arrives",
  "detay.foto": "Add a photo of the problem (optional)",
  "detay.fotoNot": "A photo helps the pro bring the right part.",
  "detay.fotoKaldir": "Remove photo",
  "detay.yorumlar": "Reviews",
  "detay.yorumSayisi": "{n} ratings",
  "detay.tumYorumlar": "Show all reviews",
  "detay.sizinYorumunuz": "Your review",
  "detay.kapaliUyari": "This pro is closed right now (opens {saat}); you can choose later today or schedule a visit.",

  "ipucu.su-sizintisi": "Turn off the main water valve; keep leaking water away from sockets and appliances.",
  "ipucu.tikali-gider": "Do not pour chemical drain openers; do not use that drain until the pro arrives.",
  "ipucu.musluk-ariza": "Close the shut-off valve under the sink.",
  "ipucu.sigorta-atiyor": "Unplug the last device you connected; do not keep resetting the fuse.",
  "ipucu.priz-yanik": "Switch off that circuit's fuse and do not touch the socket. If there is smoke or fire, call 112.",
  "ipucu.elektrik-yok": "If neighbours have no power either, it may be a general outage; keep the fridge door closed.",
  "ipucu.kapida-kaldim": "Do not force the door; keep your ID with you, the pro will ask for proof of residence.",
  "ipucu.kilit-degisimi": "Add a photo of your lock so the pro brings a matching cylinder.",
  "ipucu.anahtar-kirildi": "Do not try to pull out the broken piece yourself; it can damage the lock further.",
  "ipucu.sicak-su-yok": "Note the error code on the boiler display and try switching it off and on once.",
  "ipucu.basinc-dusuk": "Take a photo of the pressure gauge and turn the boiler off.",
  "ipucu.petek-isinmiyor": "Make sure the radiator valves are open.",
  "ipucu.camasir-makinesi": "Switch the machine off and unplug it; do not force the door.",
  "ipucu.buzdolabi": "Keep the door closed as much as possible; move perishable food somewhere cool.",
  "ipucu.bulasik-makinesi": "Unplug the machine and close its water tap.",

  "harita.etiket": "Map of pros in Istanbul",
  "harita.sen": "You",
  "harita.profil": "View profile",
  "harita.avrupa": "European side",
  "harita.asya": "Asian side",

  "karsilama.baslik": "Welcome to Ustam",
  "karsilama.slogan": "Your breakdown, our pro.",
  "karsilama.alt": "Call the nearest available pro for any breakdown at home, in your own language.",
  "karsilama.dilSec": "Choose your language",
  "karsilama.semtSec": "Which district are you in?",
  "karsilama.semtNot": "Used to show the nearest pros; it never leaves your device.",
  "karsilama.devam": "Continue",
  "karsilama.basla": "Get started",

  "genel.vazgec": "Cancel",

  "cagri.iletisim": "Contact phone",
  "cagri.telefonNot": "The pro will call this number when on the way; it is saved to your profile.",
  "cagri.telefonHata": "Enter a valid phone number.",
  "cagri.odeme": "Payment preference",
  "odeme.nakit": "Cash at the door",
  "odeme.kart": "Card at the door",
  "cagri.odemeNot": "The app takes no payment; you pay the pro when the job is done.",
  "cagri.kosullarOnay": "I have read and accept the terms of use.",
  "cagri.motorRust": "Calculated by: Rust core",
  "cagri.motorTs": "Calculated by: browser (TypeScript)",
  "cagri.olusturuldu": "Job created: {kod}",

  "is.aktif": "Active",
  "is.gecmis": "History",
  "is.aktifYok": "You have no active requests.",
  "is.gecmisYok": "You have no past jobs.",
  "asama.alindi": "Request received",
  "asama.onaylandi": "Pro accepted",
  "asama.yolda": "On the way",
  "asama.kapida": "At the door",
  "asama.tamamlandi": "Done",
  "is.varis": "Estimated arrival {saat}",
  "is.kalan": "{dk} min left",
  "is.randevu": "Appointment: {zaman}",
  "is.kapidaNot": "The pro should be at your door. Verify the code they tell you before opening.",
  "is.kopyala": "Copy code",
  "is.kopyalandi": "Code copied",
  "is.qrGoster": "Show QR code",
  "is.qrGizle": "Hide QR code",
  "is.qrEtiket": "QR code for job code {kod}",
  "is.qrNot": "The pro scans this QR to record the job.",
  "is.fiyatDokumu": "Price breakdown",
  "is.dogrulandi": "Pro verified",
  "is.bitir": "Job done",
  "is.bitirNot": "Verify the code of the pro at your door before completing the job.",
  "is.iptalBaslik": "Cancel request",
  "is.iptalSoru": "Why are you cancelling?",
  "iptal.vazgectim": "Changed my mind",
  "iptal.gecikti": "The pro is late",
  "iptal.baskasi": "Found another pro",
  "iptal.cozuldu": "The problem fixed itself",
  "is.iptalOnay": "Cancel request",
  "is.iptalEdildi": "Request cancelled",
  "is.degerlendir": "Rate",
  "is.degerlendirBaslik": "How was {usta}?",
  "is.yorumYer": "Describe your experience in a few sentences (optional)",
  "is.gonder": "Send",
  "is.tesekkur": "Thanks for your rating!",
  "is.puaniniz": "Your rating",
  "is.puanSec": "{n} stars",
  "is.tekrar": "Call again",
  "is.odeme": "Payment",
  "is.ustaArayacak": "The pro will call you on {telefon}.",

  "profil.toplamIs": "Total jobs",
  "profil.tamamlananIs": "Completed",
  "profil.harcama": "Spent",
  "profil.yorumlarim": "My reviews",
  "profil.favoriUstalar": "My favourite pros",
  "profil.favoriYok": "No favourite pros yet. Tap the heart on a pro card.",
  "profil.veri": "My data (KVKK)",
  "profil.disaAktar": "Export my data (JSON)",
  "profil.sil": "Delete all my data on this device",
  "profil.silBaslik": "Delete all data?",
  "profil.silNot": "Your profile, jobs, favourites and reviews will be permanently removed from this device. This is your right to erasure under KVKK.",
  "profil.silOnay": "Yes, delete everything",
  "profil.silindi": "All your data has been deleted.",
  "profil.surum": "Version {surum} · Core: {motor}",
  "motor.rust": "Rust (Tauri)",
  "motor.ts": "Browser (TypeScript)",

  "karsilama.atla": "Skip",
  "karsilama.ileri": "Next",
  "karsilama.adim1Baslik": "Pick the problem",
  "karsilama.adim1Metin": "Leak, power, lock, boiler… describe what happened in two taps.",
  "karsilama.adim2Baslik": "Find an available pro nearby",
  "karsilama.adim2Metin": "See distance, arrival time, rating and price range before you call.",
  "karsilama.adim3Baslik": "Track the job safely",
  "karsilama.adim3Metin": "Verify the code of the pro at your door; if it does not match, do not open.",
  "karsilama.adim": "Step {n} of {toplam}",
  "genel.cevrimdisi": "You are offline. The app keeps working because your data is on this device.",

  "liste.konumDegistir": "Change location: {semt}",
  "liste.neOldu": "What happened?",
  "liste.acilAlt": "Nearest available pro, one tap away",
  "liste.enYakin": "{usta} · ~{dk} min",
  "liste.tarifEt": "Describe the problem step by step",
  "liste.aramaOneri": "Problems",
  "liste.tumUstalar": "All pros",
  "liste.filtrele": "Filter",
  "liste.siralaEtiket": "Sort: {ad}",
  "filtre.baslik": "Filters",
  "filtre.durum": "Status",
  "filtre.mesafe": "Distance",
  "filtre.mesafeKm": "≤ {n} km",
  "filtre.puan": "Minimum rating",
  "filtre.fiyat": "Call-out fee",
  "filtre.fiyatEnFazla": "≤ {tutar}",
  "filtre.dil": "Language spoken",
  "filtre.tumu": "Any",
  "filtre.temizle": "Clear",
  "filtre.goster": "Show {n} pros",
  "sirala.baslik": "Sort by",
  "sirala.onerilenAciklama": "Availability, distance, rating, response time and language together",
  "sirala.yakinAciklama": "Closest to you first",
  "sirala.puanAciklama": "Highest average rating first",
  "sirala.fiyatAciklama": "Lowest call-out fee first",
  "neden.ac": "Why recommended?",
  "neden.baslik": "Why we recommend this pro",
  "neden.musait": "Available now and can come right away",
  "neden.yakin": "{km} km from you",
  "neden.puan": "{puan} average rating",
  "neden.hizli": "Responds in {dk} min on average",
  "neden.dil": "Speaks {dil}",
  "neden.fiyat": "Call-out fee below average",
  "neden.not": "Ranking uses only this information and fixed rules; there is no paid promotion.",
  "kart.simdiGelebilir": "Can come now · ~{dk} min",
  "kart.mesgulSonra": "Busy · free in ~{dk} min",
  "kart.cikisDan": "Call-out {tutar}",
  "sihirbaz.alanSoru": "What area is the problem in?",
  "sihirbaz.sorunSoru": "Which is closest?",
  "sihirbaz.aciliyetSoru": "How urgent is it?",
  "sihirbaz.hemen": "It is happening now, come right away",
  "sihirbaz.bugun": "Sometime today",
  "sihirbaz.randevu": "Not urgent, an appointment is fine",
  "sihirbaz.sonuc": "Pros for you",
  "sihirbaz.sonucYok": "No pro matches right now. Try the appointment option.",
  "sihirbaz.sec": "Choose this pro",
  "harita.listeyeDon": "Back to list",

  "detay.hemenVaris": "The pro could be at your door in about {dk} min.",
  "detay.acilAra": "If there is smoke, fire or an injury, call 112 first",
  "detay.fotoGizlilik": "The photo stays only on this device and is saved in a reduced size; it is never sent to a server.",
  "detay.fotoHata": "This file cannot be used. Choose a photo smaller than 15 MB.",
  "detay.fotoSec": "Take or choose a photo",
  "detay.varis": "Arrival",
  "detay.yarin": "Tomorrow",
  "cagri.adimUsta": "Pro",
  "cagri.adimOnay": "Confirm",
  "cagri.degistir": "Change",
  "cagri.tekrarDene": "Try again",
  "fiyat.nasil": "How is this calculated?",
  "fiyat.kuralCikis": "The call-out fee is the pro's fixed fee.",
  "fiyat.kuralAcil": "\"Right now\" requests add a {tutar} emergency fee.",
  "fiyat.kuralGece": "Visits between 22:00 and 08:00 add 25% of the call-out fee.",
  "fiyat.kuralPazar": "Sunday visits add 15% of the call-out fee.",
  "fiyat.kuralIscilik": "Labour is an estimated range for this problem type; the pro confirms the exact amount on site.",

  "is.guvenlikKodu": "Security code",
  "is.yanlisBaslik": "Do not open the door",
  "is.yanlisMetin": "This code does not belong to your job. Ask the pro to repeat it; if you are still unsure, call 112.",
  "is.dogruBaslik": "Code is correct",
  "is.dogruMetin": "This is the pro you called. You can open the door.",
  "is.ustaBilgi": "{kategori} · {semt}",
  "profil.hesabim": "My account",
  "profil.konum": "Location",
  "profil.gorunum": "Appearance",
  "profil.gizlilik": "Privacy",
  "profil.verilenPuan": "Your avg. rating",
  "profil.favoriBosBaslik": "No favourite pros yet",
  "profil.favoriBosMetin": "Save the pros you like to reach them faster next time something breaks.",
  "profil.ustalaraGoz": "Browse pros",
};

const ar: Record<Anahtar, string> = {

  "nav.ustalar": "الفنّيون",
  "nav.cagri": "الطلب",
  "nav.isEmirleri": "طلباتي",
  "nav.profil": "حسابي",

  "tema.degistir": "المظهر: {ad} (اضغط للتغيير)",
  "tema.sistem": "النظام",
  "tema.gunduz": "فاتح",
  "tema.gece": "داكن",
  "genel.kapat": "إغلاق",
  "durum.yukleniyor": "جارٍ التحميل…",
  "durum.hataBaslik": "حدث خطأ ما",
  "durum.tekrarDene": "إعادة المحاولة",
  "durum.ustalarHata": "تعذّر تحميل قائمة الفنّيين. حاول مرة أخرى بعد قليل.",
  "durum.isEmirleriHata": "تعذّرت قراءة طلباتك. حاول مرة أخرى؛ وإن استمرت المشكلة فأعد فتح التطبيق.",
  "durum.ustaYokBaslik": "لا يوجد فنّيون في هذه المنطقة بعد",
  "durum.ustaYokMetin": "سينضم فنّيون جدد قريبًا. يمكنك أيضًا البحث باختيار حيّ آخر.",
  "durum.suzgecBosMetin": "غيّر كلمات البحث أو عوامل التصفية.",
  "durum.aktifYokMetin": "عندما تطلب فنّيًا ستتابع العمل مباشرة هنا.",
  "durum.gecmisYokMetin": "تظهر هنا الأعمال المكتملة والملغاة.",
  "dil.sec": "اختر اللغة",

  "kategori.tesisat": "سباكة",
  "kategori.elektrik": "كهرباء",
  "kategori.cilingir": "أقفال ومفاتيح",
  "kategori.kombi": "غلاية التدفئة",
  "kategori.beyaz-esya": "أجهزة منزلية",

  "sorun.su-sizintisi": "تسرّب مياه",
  "sorun.tikali-gider": "انسداد المصرف",
  "sorun.musluk-ariza": "عطل في الحنفية",
  "sorun.sigorta-atiyor": "القاطع الكهربائي يفصل باستمرار",
  "sorun.priz-yanik": "رائحة احتراق من المقبس",
  "sorun.elektrik-yok": "لا توجد كهرباء في المنزل",
  "sorun.kapida-kaldim": "أنا عالق خارج الباب",
  "sorun.kilit-degisimi": "تغيير القفل",
  "sorun.anahtar-kirildi": "انكسر المفتاح داخل القفل",
  "sorun.sicak-su-yok": "لا يوجد ماء ساخن",
  "sorun.basinc-dusuk": "ضغط الغلاية ينخفض",
  "sorun.petek-isinmiyor": "المشعات لا تسخن",
  "sorun.camasir-makinesi": "الغسالة لا تصرّف الماء",
  "sorun.buzdolabi": "الثلاجة لا تبرّد",
  "sorun.bulasik-makinesi": "غسالة الصحون لا تعمل",

  "aciliyet.hemen": "فورًا",
  "aciliyet.bugun": "اليوم",
  "aciliyet.randevu": "موعد لاحق",

  "liste.baslik": "فنّيون بالقرب منك",
  "liste.arama": "ابحث بالاسم أو الاختصاص أو الحي",
  "liste.tumu": "الكل",
  "liste.sadeceMusait": "المتاحون فقط",
  "liste.sonuc": "{n} فنّي",
  "liste.bos": "لا يوجد فنّي يطابق بحثك.",

  "kart.musait": "متاح الآن",
  "kart.mesgul": "مشغول",
  "kart.km": "{n} كم",
  "kart.yorum": "{n} تقييم",
  "kart.cikis": "رسوم الزيارة {tutar}",

  "detay.deneyim": "الخبرة",
  "detay.yil": "{n} سنة",
  "detay.tamamlanan": "أعمال منجزة",
  "detay.sorunSec": "ما هي المشكلة؟",
  "detay.aciliyet": "متى يأتي الفنّي؟",
  "detay.saat": "وقت الزيارة",
  "detay.tarih": "التاريخ",
  "detay.acilUcret": "+{tutar} رسوم الطوارئ",
  "detay.bugunSaatYok": "لا توجد مواعيد متبقية اليوم، يرجى اختيار موعد لاحق.",
  "detay.adres": "ملاحظة العنوان",
  "detay.adresOrnek": "الطابق، رقم الشقة، اسم الجرس…",
  "detay.ustayaIletilen": "سيُرسل إلى الفنّي بالتركية:",
  "detay.mesgulUyari": "هذا الفنّي مشغول الآن؛ يمكنك حجز موعد لاحق فقط.",
  "detay.cagirKisa": "اطلب الفنّي",

  "cagri.baslik": "ملخّص الطلب",
  "cagri.bos": "لم تُنشئ أي طلب بعد.",
  "cagri.ustaSec": "← اختر فنّيًا",
  "cagri.sorun": "المشكلة",
  "cagri.zaman": "الوقت",
  "cagri.adres": "ملاحظة العنوان",
  "cagri.cikis": "رسوم الزيارة",
  "cagri.acil": "رسوم الطوارئ",
  "cagri.toplam": "الإجمالي التقديري",
  "cagri.gece": "رسوم إضافية ليلية (22:00–08:00)",
  "cagri.pazar": "رسوم إضافية يوم الأحد",
  "cagri.iscilik": "تكلفة العمل التقديرية",
  "cagri.not": "يحدّد الفنّي تكلفة القطع والعمل في الموقع.",
  "cagri.onayla": "تأكيد الطلب",
  "cagri.isleniyor": "جارٍ إنشاء رمز الطلب…",
  "cagri.vazgec": "إلغاء",
  "cagri.hata": "تعذّر إنشاء الرمز:",

  "is.baslik": "طلباتي",
  "is.kod": "رمز الطلب",
  "is.kodNot": "اطلب من الفنّي أن يذكر هذا الرمز عند الباب.",
  "is.iptal": "إلغاء",
  "is.dogrulaBaslik": "تحقّق من الفنّي عند الباب",
  "is.dogrulaYer": "الرمز الذي يذكره الفنّي",
  "is.dogrulaBtn": "تحقّق",
  "is.yanlis": "هذا الرمز غير موجود في طلباتك. لا تفتح الباب!",
  "is.formatHatali": "صيغة الرمز غير صحيحة (مثال: UST-ELK-1210-K7QZ).",
  "is.kontrolHatali": "ربما كُتب الرمز بشكل خاطئ: حرف التحقق لا يطابق. اطلب من الفنّي تكراره.",

  "durum.tamamlandi": "منجز",
  "durum.iptal": "ملغى",

  "profil.misafir": "مستخدم زائر",
  "profil.ad": "الاسم الكامل",
  "profil.telefon": "الهاتف",
  "profil.adres": "العنوان",
  "profil.kaydet": "حفظ",
  "profil.kaydedildi": "تمّ الحفظ ✓",
  "profil.ayarlar": "الإعدادات",
  "profil.dil": "لغة التطبيق",
  "profil.tema": "المظهر",
  "profil.bilgi": "معلومات وشروط",

  "sayfa.hakkinda": "حول التطبيق",
  "sayfa.iletisim": "اتصل بنا",
  "sayfa.kosullar": "شروط الاستخدام",
  "sayfa.gizlilik": "سياسة الخصوصية",

  "iletisim.aciklama": "راسلنا لأي سؤال أو اقتراح أو للانضمام كفنّي. نرد عادةً خلال يوم عمل واحد.",
  "iletisim.ad": "اسمك",
  "iletisim.eposta": "البريد الإلكتروني",
  "iletisim.konu": "الموضوع",
  "iletisim.mesaj": "رسالتك",
  "iletisim.ipucu": "املأ جميع الحقول؛ يجب ألا تقل الرسالة عن 10 أحرف.",
  "iletisim.gonder": "إرسال",
  "iletisim.gonderiliyor": "جارٍ الإرسال…",
  "iletisim.basarili": "تم إرسال رسالتك. شكرًا لك!",
  "konu.genel": "سؤال عام",
  "konu.usta": "أريد الانضمام كفنّي",
  "konu.sikayet": "شكوى",
  "konu.oneri": "اقتراح",

  "liste.merhaba": "مرحبًا",
  "liste.merhabaAd": "مرحبًا، {ad}",
  "liste.soru": "ماذا نصلح اليوم؟",
  "liste.konumSec": "اختر حيّك",
  "liste.acilBaslik": "حالة طارئة؟ أقرب فنّي متاح",
  "liste.acilYok": "لا يوجد فنّي متاح الآن",
  "liste.aktifYolda": "{usta} في الطريق · حوالي {dk} دقيقة",
  "liste.aktifRandevu": "{usta} · موعد {zaman}",
  "liste.favoriler": "المفضّلة",
  "liste.dilimiKonusan": "يتحدث العربية",
  "liste.sirala": "ترتيب",
  "liste.gorunum": "طريقة العرض",
  "liste.liste": "قائمة",
  "liste.harita": "خريطة",
  "liste.filtreTemizle": "مسح الفلاتر",
  "sirala.onerilen": "المقترح",
  "sirala.yakin": "الأقرب",
  "sirala.puan": "الأعلى تقييمًا",
  "sirala.fiyat": "الأقل سعرًا",

  "kart.kapali": "مغلق · يفتح {saat}",
  "kart.dk": "~{dk} د",
  "kart.favoriEkle": "إضافة إلى المفضّلة",
  "kart.favoriCikar": "إزالة من المفضّلة",
  "kart.favoriEklendi": "أُضيف {ad} إلى المفضّلة",
  "kart.favoriCikarildi": "أُزيل {ad} من المفضّلة",

  "rozet.dogrulanmis": "هوية موثّقة",
  "rozet.sigortali": "عمل مؤمَّن",
  "rozet.7-24": "خدمة 24/7",
  "rozet.hizli-yanit": "استجابة سريعة",

  "detay.geri": "رجوع",
  "detay.yanit": "زمن الاستجابة",
  "detay.mesafe": "المسافة",
  "detay.calisma": "ساعات العمل",
  "detay.724": "24 ساعة، 7 أيام",
  "detay.diller": "اللغات التي يتحدثها",
  "detay.dilinizi": "يتحدث لغتك",
  "detay.sure": "عمل لمدة ~{dk} دقيقة",
  "detay.guvenlik": "إلى أن يصل الفنّي",
  "detay.foto": "أضف صورة للعطل (اختياري)",
  "detay.fotoNot": "تساعد الصورة الفنّي على إحضار القطعة المناسبة.",
  "detay.fotoKaldir": "إزالة الصورة",
  "detay.yorumlar": "التقييمات",
  "detay.yorumSayisi": "{n} تقييم",
  "detay.tumYorumlar": "عرض كل التقييمات",
  "detay.sizinYorumunuz": "تقييمك",
  "detay.kapaliUyari": "هذا الفنّي مغلق الآن (يفتح {saat})؛ يمكنك اختيار وقت لاحق اليوم أو حجز موعد.",

  "ipucu.su-sizintisi": "أغلق محبس المياه الرئيسي، وأبعد المياه المتسرّبة عن المقابس والأجهزة الكهربائية.",
  "ipucu.tikali-gider": "لا تسكب مواد كيميائية لفتح الانسداد، ولا تستخدم هذا المصرف حتى يصل الفنّي.",
  "ipucu.musluk-ariza": "أغلق المحبس الفرعي تحت المغسلة.",
  "ipucu.sigorta-atiyor": "افصل آخر جهاز وصلته، ولا تُعِد رفع القاطع مرارًا.",
  "ipucu.priz-yanik": "افصل قاطع هذا الخط ولا تلمس المقبس. إن كان هناك دخان أو نار فاتصل بـ 112.",
  "ipucu.elektrik-yok": "إن لم تكن الكهرباء عند الجيران أيضًا فقد يكون انقطاعًا عامًا؛ لا تفتح باب الثلاجة.",
  "ipucu.kapida-kaldim": "لا تحاول كسر الباب؛ احتفظ بهويتك معك، فالفنّي سيطلب ما يثبت سكنك.",
  "ipucu.kilit-degisimi": "أضف صورة لنوع القفل كي يحضر الفنّي الأسطوانة المناسبة.",
  "ipucu.anahtar-kirildi": "لا تحاول إخراج القطعة المكسورة بنفسك؛ قد يتضرر القفل أكثر.",
  "ipucu.sicak-su-yok": "دوّن رمز الخطأ الظاهر على شاشة الغلاية، وجرّب إطفاءها وتشغيلها مرة واحدة.",
  "ipucu.basinc-dusuk": "التقط صورة لمؤشر الضغط وأطفئ الغلاية.",
  "ipucu.petek-isinmiyor": "تأكد من أن صمامات المشعات مفتوحة.",
  "ipucu.camasir-makinesi": "أطفئ الغسالة وافصل قابسها، ولا تفتح الباب بالقوة.",
  "ipucu.buzdolabi": "أبقِ الباب مغلقًا قدر الإمكان، وانقل الأطعمة القابلة للتلف إلى مكان بارد.",
  "ipucu.bulasik-makinesi": "افصل قابس الجهاز وأغلق صنبور المياه الخاص به.",

  "harita.etiket": "خريطة الفنّيين في إسطنبول",
  "harita.sen": "أنت",
  "harita.profil": "عرض الملف",
  "harita.avrupa": "الجانب الأوروبي",
  "harita.asya": "الجانب الآسيوي",

  "karsilama.baslik": "مرحبًا بك في Ustam",
  "karsilama.slogan": "العطل عليك، والفنّي علينا.",
  "karsilama.alt": "اطلب أقرب فنّي متاح لأي عطل في منزلك، وبلغتك.",
  "karsilama.dilSec": "اختر لغتك",
  "karsilama.semtSec": "في أي حيّ تسكن؟",
  "karsilama.semtNot": "يُستخدم لعرض أقرب الفنّيين، ولا يغادر جهازك.",
  "karsilama.devam": "متابعة",
  "karsilama.basla": "ابدأ",

  "genel.vazgec": "إلغاء",

  "cagri.iletisim": "هاتف التواصل",
  "cagri.telefonNot": "سيتصل بك الفنّي على هذا الرقم عند انطلاقه؛ ويُحفظ الرقم في ملفك.",
  "cagri.telefonHata": "أدخل رقم هاتف صحيحًا.",
  "cagri.odeme": "طريقة الدفع المفضّلة",
  "odeme.nakit": "نقدًا عند الباب",
  "odeme.kart": "بالبطاقة عند الباب",
  "cagri.odemeNot": "التطبيق لا يتقاضى أي مبلغ؛ تدفع للفنّي بعد انتهاء العمل.",
  "cagri.kosullarOnay": "قرأت شروط الاستخدام وأوافق عليها.",
  "cagri.motorRust": "الحساب: نواة Rust",
  "cagri.motorTs": "الحساب: المتصفح (TypeScript)",
  "cagri.olusturuldu": "تم إنشاء الطلب: {kod}",

  "is.aktif": "النشطة",
  "is.gecmis": "السابقة",
  "is.aktifYok": "لا توجد لديك طلبات نشطة.",
  "is.gecmisYok": "لا توجد لديك طلبات سابقة.",
  "asama.alindi": "تم استلام الطلب",
  "asama.onaylandi": "وافق الفنّي",
  "asama.yolda": "في الطريق",
  "asama.kapida": "عند الباب",
  "asama.tamamlandi": "منجز",
  "is.varis": "الوصول المتوقع {saat}",
  "is.kalan": "متبقٍ {dk} دقيقة",
  "is.randevu": "الموعد: {zaman}",
  "is.kapidaNot": "يُفترض أن الفنّي عند بابك. تحقّق من الرمز الذي يذكره قبل أن تفتح.",
  "is.kopyala": "نسخ الرمز",
  "is.kopyalandi": "تم نسخ الرمز",
  "is.qrGoster": "إظهار رمز QR",
  "is.qrGizle": "إخفاء رمز QR",
  "is.qrEtiket": "رمز QR لرمز الطلب {kod}",
  "is.qrNot": "يمسح الفنّي رمز QR هذا لتسجيل العمل.",
  "is.fiyatDokumu": "تفصيل السعر",
  "is.dogrulandi": "تم التحقق من الفنّي",
  "is.bitir": "انتهى العمل",
  "is.bitirNot": "تحقّق من رمز الفنّي عند الباب قبل إنهاء العمل.",
  "is.iptalBaslik": "إلغاء الطلب",
  "is.iptalSoru": "ما سبب الإلغاء؟",
  "iptal.vazgectim": "غيّرت رأيي",
  "iptal.gecikti": "تأخّر الفنّي",
  "iptal.baskasi": "وجدت فنّيًا آخر",
  "iptal.cozuldu": "حُلّت المشكلة من تلقاء نفسها",
  "is.iptalOnay": "إلغاء الطلب",
  "is.iptalEdildi": "تم إلغاء الطلب",
  "is.degerlendir": "قيّم",
  "is.degerlendirBaslik": "كيف كان {usta}؟",
  "is.yorumYer": "صف تجربتك في بضع جمل (اختياري)",
  "is.gonder": "إرسال",
  "is.tesekkur": "شكرًا على تقييمك!",
  "is.puaniniz": "تقييمك",
  "is.puanSec": "{n} نجوم",
  "is.tekrar": "اطلب مجددًا",
  "is.odeme": "الدفع",
  "is.ustaArayacak": "سيتصل بك الفنّي على الرقم {telefon}.",

  "profil.toplamIs": "إجمالي الطلبات",
  "profil.tamamlananIs": "المنجزة",
  "profil.harcama": "المصروف",
  "profil.yorumlarim": "تقييماتي",
  "profil.favoriUstalar": "فنّيّو المفضّلة",
  "profil.favoriYok": "لا يوجد فنّيون في المفضّلة بعد. اضغط على القلب في بطاقة الفنّي.",
  "profil.veri": "بياناتي (KVKK)",
  "profil.disaAktar": "تصدير بياناتي (JSON)",
  "profil.sil": "حذف كل بياناتي على هذا الجهاز",
  "profil.silBaslik": "هل تريد حذف كل البيانات؟",
  "profil.silNot": "سيُحذف ملفك وطلباتك ومفضّلتك وتقييماتك من هذا الجهاز نهائيًا. هذا حقك في الحذف وفق KVKK.",
  "profil.silOnay": "نعم، احذف الكل",
  "profil.silindi": "تم حذف كل بياناتك.",
  "profil.surum": "الإصدار {surum} · النواة: {motor}",
  "motor.rust": "Rust (Tauri)",
  "motor.ts": "المتصفح (TypeScript)",

  "karsilama.atla": "تخطٍّ",
  "karsilama.ileri": "التالي",
  "karsilama.adim1Baslik": "اختر العطل",
  "karsilama.adim1Metin": "تسرّب، كهرباء، قفل، غلاية… صف ما حدث بلمستين.",
  "karsilama.adim2Baslik": "اعثر على فنّي متاح قريب منك",
  "karsilama.adim2Metin": "شاهد المسافة ووقت الوصول والتقييم ونطاق السعر قبل الطلب.",
  "karsilama.adim3Baslik": "تابع الطلب بأمان",
  "karsilama.adim3Metin": "تحقّق من رمز الفنّي عند الباب؛ إن لم يطابق فلا تفتح.",
  "karsilama.adim": "الخطوة {n} من {toplam}",
  "genel.cevrimdisi": "أنت غير متصل. يواصل التطبيق العمل لأن بياناتك محفوظة على هذا الجهاز.",

  "liste.konumDegistir": "تغيير الموقع: {semt}",
  "liste.neOldu": "ماذا حدث؟",
  "liste.acilAlt": "أقرب فنّي متاح بلمسة واحدة",
  "liste.enYakin": "{usta} · ~{dk} د",
  "liste.tarifEt": "صف العطل خطوة بخطوة",
  "liste.aramaOneri": "المشكلات",
  "liste.tumUstalar": "كل الفنّيين",
  "liste.filtrele": "تصفية",
  "liste.siralaEtiket": "الترتيب: {ad}",
  "filtre.baslik": "عوامل التصفية",
  "filtre.durum": "الحالة",
  "filtre.mesafe": "المسافة",
  "filtre.mesafeKm": "≤ {n} كم",
  "filtre.puan": "أدنى تقييم",
  "filtre.fiyat": "رسوم الزيارة",
  "filtre.fiyatEnFazla": "≤ {tutar}",
  "filtre.dil": "اللغة التي يتحدثها",
  "filtre.tumu": "الكل",
  "filtre.temizle": "مسح",
  "filtre.goster": "عرض {n} فنّي",
  "sirala.baslik": "الترتيب",
  "sirala.onerilenAciklama": "التوفّر والمسافة والتقييم وزمن الاستجابة واللغة معًا",
  "sirala.yakinAciklama": "الأقرب إليك أولًا",
  "sirala.puanAciklama": "الأعلى تقييمًا أولًا",
  "sirala.fiyatAciklama": "الأقل رسوم زيارة أولًا",
  "neden.ac": "لماذا يُقترح؟",
  "neden.baslik": "لماذا نقترح هذا الفنّي؟",
  "neden.musait": "متاح الآن ويمكنه القدوم فورًا",
  "neden.yakin": "على بُعد {km} كم منك",
  "neden.puan": "متوسط التقييم {puan}",
  "neden.hizli": "يرد خلال {dk} دقيقة في المتوسط",
  "neden.dil": "يتحدث {dil}",
  "neden.fiyat": "رسوم الزيارة أقل من المتوسط",
  "neden.not": "يعتمد الترتيب على هذه المعلومات وقواعد ثابتة فقط؛ لا يوجد ترويج مدفوع.",
  "kart.simdiGelebilir": "يمكنه القدوم الآن · ~{dk} د",
  "kart.mesgulSonra": "مشغول · يتفرّغ بعد ~{dk} د",
  "kart.cikisDan": "الزيارة {tutar}",
  "sihirbaz.alanSoru": "في أي مجال المشكلة؟",
  "sihirbaz.sorunSoru": "أيّها الأقرب؟",
  "sihirbaz.aciliyetSoru": "ما مدى الاستعجال؟",
  "sihirbaz.hemen": "ما زالت مستمرة، يجب الحضور فورًا",
  "sihirbaz.bugun": "في وقت ما اليوم",
  "sihirbaz.randevu": "ليست عاجلة، يكفي موعد",
  "sihirbaz.sonuc": "فنّيون مناسبون لك",
  "sihirbaz.sonucYok": "لا يوجد فنّي مطابق الآن. جرّب خيار الموعد.",
  "sihirbaz.sec": "اختر هذا الفنّي",
  "harita.listeyeDon": "العودة إلى القائمة",

  "detay.hemenVaris": "قد يصل الفنّي إلى بابك خلال {dk} دقيقة تقريبًا.",
  "detay.acilAra": "إن كان هناك دخان أو نار أو إصابة فاتصل بـ 112 أولًا",
  "detay.fotoGizlilik": "تبقى الصورة على هذا الجهاز فقط وتُحفظ بحجم مصغّر؛ ولا تُرسل إلى أي خادم.",
  "detay.fotoHata": "لا يمكن استخدام هذا الملف. اختر صورة أصغر من 15 ميغابايت.",
  "detay.fotoSec": "التقط صورة أو اخترها",
  "detay.varis": "الوصول",
  "detay.yarin": "غدًا",
  "cagri.adimUsta": "الفنّي",
  "cagri.adimOnay": "التأكيد",
  "cagri.degistir": "تغيير",
  "cagri.tekrarDene": "أعد المحاولة",
  "fiyat.nasil": "كيف حُسب السعر؟",
  "fiyat.kuralCikis": "رسوم الزيارة هي الأجر الثابت للفنّي.",
  "fiyat.kuralAcil": "تُضاف رسوم طوارئ قدرها {tutar} للطلبات \"فورًا\".",
  "fiyat.kuralGece": "إذا كانت الزيارة بين 22:00 و08:00 تُضاف 25% من رسوم الزيارة.",
  "fiyat.kuralPazar": "إذا كانت الزيارة يوم الأحد تُضاف 15% من رسوم الزيارة.",
  "fiyat.kuralIscilik": "أجر العمل نطاق تقديري حسب نوع المشكلة؛ ويحدّد الفنّي المبلغ النهائي في الموقع.",

  "is.guvenlikKodu": "رمز الأمان",
  "is.yanlisBaslik": "لا تفتح الباب",
  "is.yanlisMetin": "هذا الرمز لا يخص طلبك. اطلب من الفنّي تكراره؛ وإن بقيت تشك فاتصل بـ 112.",
  "is.dogruBaslik": "الرمز صحيح",
  "is.dogruMetin": "هذا هو الفنّي الذي طلبته. يمكنك فتح الباب.",
  "is.ustaBilgi": "{kategori} · {semt}",
  "profil.hesabim": "حسابي",
  "profil.konum": "الموقع",
  "profil.gorunum": "المظهر",
  "profil.gizlilik": "الخصوصية",
  "profil.verilenPuan": "متوسط تقييمك",
  "profil.favoriBosBaslik": "لا يوجد فنّيون في المفضّلة بعد",
  "profil.favoriBosMetin": "احفظ الفنّيين الذين أعجبوك لتصل إليهم أسرع عند العطل القادم.",
  "profil.ustalaraGoz": "تصفّح الفنّيين",
};

const fa: Record<Anahtar, string> = {

  "nav.ustalar": "استادکاران",
  "nav.cagri": "درخواست",
  "nav.isEmirleri": "سفارش‌های من",
  "nav.profil": "پروفایل",

  "tema.degistir": "پوسته: {ad} (برای تغییر لمس کنید)",
  "tema.sistem": "سیستم",
  "tema.gunduz": "روشن",
  "tema.gece": "تاریک",
  "genel.kapat": "بستن",
  "durum.yukleniyor": "در حال بارگذاری…",
  "durum.hataBaslik": "مشکلی پیش آمد",
  "durum.tekrarDene": "تلاش دوباره",
  "durum.ustalarHata": "فهرست استادکاران بارگذاری نشد. کمی بعد دوباره تلاش کنید.",
  "durum.isEmirleriHata": "سفارش‌های شما خوانده نشد. دوباره تلاش کنید؛ اگر مشکل ادامه داشت برنامه را دوباره باز کنید.",
  "durum.ustaYokBaslik": "هنوز استادکاری در این منطقه نیست",
  "durum.ustaYokMetin": "به‌زودی استادکاران تازه اضافه می‌شوند. می‌توانید محله دیگری را هم انتخاب کنید.",
  "durum.suzgecBosMetin": "کلمه‌های جست‌وجو یا فیلترها را تغییر دهید.",
  "durum.aktifYokMetin": "وقتی استادکاری را صدا بزنید، کار را اینجا زنده دنبال می‌کنید.",
  "durum.gecmisYokMetin": "کارهای انجام‌شده و لغوشده اینجا فهرست می‌شوند.",
  "dil.sec": "انتخاب زبان",

  "kategori.tesisat": "لوله‌کشی",
  "kategori.elektrik": "برق‌کاری",
  "kategori.cilingir": "کلیدسازی",
  "kategori.kombi": "پکیج",
  "kategori.beyaz-esya": "لوازم خانگی",

  "sorun.su-sizintisi": "نشت آب",
  "sorun.tikali-gider": "گرفتگی فاضلاب",
  "sorun.musluk-ariza": "خرابی شیر آب",
  "sorun.sigorta-atiyor": "فیوز مدام می‌پرد",
  "sorun.priz-yanik": "پریز بوی سوختگی می‌دهد",
  "sorun.elektrik-yok": "برق خانه قطع است",
  "sorun.kapida-kaldim": "پشت در مانده‌ام",
  "sorun.kilit-degisimi": "تعویض قفل",
  "sorun.anahtar-kirildi": "کلید داخل قفل شکسته",
  "sorun.sicak-su-yok": "آب گرم نداریم",
  "sorun.basinc-dusuk": "فشار پکیج افت می‌کند",
  "sorun.petek-isinmiyor": "شوفاژها گرم نمی‌شوند",
  "sorun.camasir-makinesi": "ماشین لباسشویی آب را تخلیه نمی‌کند",
  "sorun.buzdolabi": "یخچال خنک نمی‌کند",
  "sorun.bulasik-makinesi": "ماشین ظرفشویی کار نمی‌کند",

  "aciliyet.hemen": "همین الان",
  "aciliyet.bugun": "امروز",
  "aciliyet.randevu": "نوبت بعدی",

  "liste.baslik": "استادکاران نزدیک شما",
  "liste.arama": "جستجوی نام، تخصص یا محله",
  "liste.tumu": "همه",
  "liste.sadeceMusait": "فقط در دسترس",
  "liste.sonuc": "{n} استادکار",
  "liste.bos": "استادکاری مطابق جستجوی شما پیدا نشد.",

  "kart.musait": "الان در دسترس",
  "kart.mesgul": "مشغول",
  "kart.km": "{n} کیلومتر",
  "kart.yorum": "{n} نظر",
  "kart.cikis": "هزینه ایاب و ذهاب {tutar}",

  "detay.deneyim": "سابقه",
  "detay.yil": "{n} سال",
  "detay.tamamlanan": "کارهای انجام‌شده",
  "detay.sorunSec": "مشکل شما چیست؟",
  "detay.aciliyet": "کی بیاید؟",
  "detay.saat": "ساعت بازدید",
  "detay.tarih": "تاریخ",
  "detay.acilUcret": "+{tutar} هزینه فوری",
  "detay.bugunSaatYok": "برای امروز وقت خالی نمانده، لطفاً نوبت بعدی را انتخاب کنید.",
  "detay.adres": "یادداشت آدرس",
  "detay.adresOrnek": "طبقه، شماره واحد، نام روی زنگ…",
  "detay.ustayaIletilen": "به زبان ترکی برای استادکار ارسال می‌شود:",
  "detay.mesgulUyari": "این استادکار الان مشغول است؛ فقط می‌توانید نوبت بگیرید.",
  "detay.cagirKisa": "درخواست استادکار",

  "cagri.baslik": "خلاصه درخواست",
  "cagri.bos": "هنوز درخواستی ثبت نکرده‌اید.",
  "cagri.ustaSec": "← یک استادکار انتخاب کنید",
  "cagri.sorun": "مشکل",
  "cagri.zaman": "زمان",
  "cagri.adres": "یادداشت آدرس",
  "cagri.cikis": "هزینه ایاب و ذهاب",
  "cagri.acil": "هزینه فوری",
  "cagri.toplam": "جمع تقریبی",
  "cagri.gece": "هزینه اضافه شبانه (22:00–08:00)",
  "cagri.pazar": "هزینه اضافه یکشنبه",
  "cagri.iscilik": "دستمزد تقریبی",
  "cagri.not": "هزینه قطعات و دستمزد را استادکار در محل تعیین می‌کند.",
  "cagri.onayla": "تأیید درخواست",
  "cagri.isleniyor": "در حال ساخت کد سفارش…",
  "cagri.vazgec": "انصراف",
  "cagri.hata": "ساخت کد ممکن نشد:",

  "is.baslik": "سفارش‌های من",
  "is.kod": "کد سفارش",
  "is.kodNot": "از استادکار بخواهید این کد را دم در بگوید.",
  "is.iptal": "لغو",
  "is.dogrulaBaslik": "استادکار پشت در را تأیید کنید",
  "is.dogrulaYer": "کدی که استادکار می‌گوید",
  "is.dogrulaBtn": "بررسی",
  "is.yanlis": "این کد در سفارش‌های شما نیست. در را باز نکنید!",
  "is.formatHatali": "قالب کد نادرست است (مثال: UST-ELK-1210-K7QZ).",
  "is.kontrolHatali": "شاید کد اشتباه وارد شده: نویسه کنترلی مطابقت ندارد. از استادکار بخواهید دوباره بگوید.",

  "durum.tamamlandi": "انجام شد",
  "durum.iptal": "لغو شد",

  "profil.misafir": "کاربر مهمان",
  "profil.ad": "نام و نام خانوادگی",
  "profil.telefon": "تلفن",
  "profil.adres": "آدرس",
  "profil.kaydet": "ذخیره",
  "profil.kaydedildi": "ذخیره شد ✓",
  "profil.ayarlar": "تنظیمات",
  "profil.dil": "زبان برنامه",
  "profil.tema": "پوسته",
  "profil.bilgi": "اطلاعات و قوانین",

  "sayfa.hakkinda": "درباره ما",
  "sayfa.iletisim": "تماس با ما",
  "sayfa.kosullar": "شرایط استفاده",
  "sayfa.gizlilik": "سیاست حریم خصوصی",

  "iletisim.aciklama": "برای سؤال، پیشنهاد یا پیوستن به‌عنوان استادکار به ما پیام دهید. معمولاً ظرف ۱ روز کاری پاسخ می‌دهیم.",
  "iletisim.ad": "نام شما",
  "iletisim.eposta": "ایمیل",
  "iletisim.konu": "موضوع",
  "iletisim.mesaj": "پیام شما",
  "iletisim.ipucu": "همه فیلدها را پر کنید؛ پیام باید دست‌کم ۱۰ کاراکتر باشد.",
  "iletisim.gonder": "ارسال",
  "iletisim.gonderiliyor": "در حال ارسال…",
  "iletisim.basarili": "پیام شما ارسال شد. سپاسگزاریم!",
  "konu.genel": "سؤال عمومی",
  "konu.usta": "می‌خواهم به‌عنوان استادکار بپیوندم",
  "konu.sikayet": "شکایت",
  "konu.oneri": "پیشنهاد",

  "liste.merhaba": "سلام",
  "liste.merhabaAd": "سلام، {ad}",
  "liste.soru": "چه چیزی را تعمیر کنیم؟",
  "liste.konumSec": "محله خود را انتخاب کنید",
  "liste.acilBaslik": "فوری است؟ نزدیک‌ترین استادکار در دسترس",
  "liste.acilYok": "الان استادکاری در دسترس نیست",
  "liste.aktifYolda": "{usta} در راه است · حدود {dk} دقیقه",
  "liste.aktifRandevu": "{usta} · نوبت {zaman}",
  "liste.favoriler": "علاقه‌مندی‌ها",
  "liste.dilimiKonusan": "فارسی صحبت می‌کند",
  "liste.sirala": "مرتب‌سازی",
  "liste.gorunum": "نمایش",
  "liste.liste": "فهرست",
  "liste.harita": "نقشه",
  "liste.filtreTemizle": "پاک کردن فیلترها",
  "sirala.onerilen": "پیشنهادی",
  "sirala.yakin": "نزدیک‌ترین",
  "sirala.puan": "بالاترین امتیاز",
  "sirala.fiyat": "ارزان‌ترین",

  "kart.kapali": "بسته · ساعت {saat} باز می‌شود",
  "kart.dk": "~{dk} دقیقه",
  "kart.favoriEkle": "افزودن به علاقه‌مندی‌ها",
  "kart.favoriCikar": "حذف از علاقه‌مندی‌ها",
  "kart.favoriEklendi": "{ad} به علاقه‌مندی‌ها اضافه شد",
  "kart.favoriCikarildi": "{ad} از علاقه‌مندی‌ها حذف شد",

  "rozet.dogrulanmis": "هویت تأییدشده",
  "rozet.sigortali": "کار بیمه‌شده",
  "rozet.7-24": "خدمات شبانه‌روزی",
  "rozet.hizli-yanit": "پاسخ سریع",

  "detay.geri": "بازگشت",
  "detay.yanit": "زمان پاسخ",
  "detay.mesafe": "فاصله",
  "detay.calisma": "ساعات کاری",
  "detay.724": "۲۴ ساعته، ۷ روز هفته",
  "detay.diller": "زبان‌هایی که صحبت می‌کند",
  "detay.dilinizi": "به زبان شما صحبت می‌کند",
  "detay.sure": "کار حدود {dk} دقیقه",
  "detay.guvenlik": "تا رسیدن استادکار",
  "detay.foto": "عکس خرابی را اضافه کنید (اختیاری)",
  "detay.fotoNot": "عکس به استادکار کمک می‌کند قطعه درست را بیاورد.",
  "detay.fotoKaldir": "حذف عکس",
  "detay.yorumlar": "نظرها",
  "detay.yorumSayisi": "{n} امتیاز",
  "detay.tumYorumlar": "نمایش همه نظرها",
  "detay.sizinYorumunuz": "نظر شما",
  "detay.kapaliUyari": "این استادکار الان بسته است (ساعت {saat} باز می‌شود)؛ می‌توانید ساعتی دیرتر در امروز یا نوبت بعدی را انتخاب کنید.",

  "ipucu.su-sizintisi": "شیر اصلی آب را ببندید و آب نشتی را از پریزها و وسایل برقی دور نگه دارید.",
  "ipucu.tikali-gider": "مواد شیمیایی لوله‌بازکن نریزید و تا آمدن استادکار از آن فاضلاب استفاده نکنید.",
  "ipucu.musluk-ariza": "شیر فرعی زیر روشویی را ببندید.",
  "ipucu.sigorta-atiyor": "آخرین وسیله‌ای را که وصل کرده‌اید از برق بکشید و فیوز را پشت سر هم بالا نزنید.",
  "ipucu.priz-yanik": "فیوز آن خط را قطع کنید و به پریز دست نزنید. اگر دود یا آتش هست با ۱۱۲ تماس بگیرید.",
  "ipucu.elektrik-yok": "اگر برق همسایه‌ها هم قطع است شاید قطعی عمومی باشد؛ در یخچال را باز نکنید.",
  "ipucu.kapida-kaldim": "در را به زور باز نکنید؛ کارت شناسایی همراهتان باشد، استادکار مدرک سکونت می‌خواهد.",
  "ipucu.kilit-degisimi": "عکس قفل خود را اضافه کنید تا استادکار سیلندر مناسب را بیاورد.",
  "ipucu.anahtar-kirildi": "خودتان تکه شکسته را بیرون نکشید؛ ممکن است قفل بیشتر آسیب ببیند.",
  "ipucu.sicak-su-yok": "کد خطای روی صفحه پکیج را یادداشت کنید و یک بار آن را خاموش و روشن کنید.",
  "ipucu.basinc-dusuk": "از نشانگر فشار عکس بگیرید و پکیج را خاموش کنید.",
  "ipucu.petek-isinmiyor": "مطمئن شوید شیرهای شوفاژها باز هستند.",
  "ipucu.camasir-makinesi": "ماشین را خاموش و از برق جدا کنید؛ در آن را به زور باز نکنید.",
  "ipucu.buzdolabi": "تا جای ممکن در یخچال را بسته نگه دارید و مواد فاسدشدنی را به جای خنک ببرید.",
  "ipucu.bulasik-makinesi": "دوشاخه دستگاه را بکشید و شیر آب آن را ببندید.",

  "harita.etiket": "نقشه استادکاران در استانبول",
  "harita.sen": "شما",
  "harita.profil": "دیدن پروفایل",
  "harita.avrupa": "بخش اروپایی",
  "harita.asya": "بخش آسیایی",

  "karsilama.baslik": "به Ustam خوش آمدید",
  "karsilama.slogan": "خرابی با شما، استادکار با ما.",
  "karsilama.alt": "برای هر خرابی در خانه، نزدیک‌ترین استادکار در دسترس را به زبان خودتان خبر کنید.",
  "karsilama.dilSec": "زبان خود را انتخاب کنید",
  "karsilama.semtSec": "در کدام محله هستید؟",
  "karsilama.semtNot": "برای نشان دادن نزدیک‌ترین استادکاران استفاده می‌شود و از دستگاه شما خارج نمی‌شود.",
  "karsilama.devam": "ادامه",
  "karsilama.basla": "شروع",

  "genel.vazgec": "انصراف",

  "cagri.iletisim": "تلفن تماس",
  "cagri.telefonNot": "استادکار وقتی راه افتاد با این شماره تماس می‌گیرد؛ شماره در پروفایل شما ذخیره می‌شود.",
  "cagri.telefonHata": "یک شماره تلفن معتبر وارد کنید.",
  "cagri.odeme": "روش پرداخت",
  "odeme.nakit": "نقدی دم در",
  "odeme.kart": "کارت دم در",
  "cagri.odemeNot": "برنامه هیچ پرداختی دریافت نمی‌کند؛ پس از پایان کار به استادکار پرداخت می‌کنید.",
  "cagri.kosullarOnay": "شرایط استفاده را خواندم و می‌پذیرم.",
  "cagri.motorRust": "محاسبه: هسته Rust",
  "cagri.motorTs": "محاسبه: مرورگر (TypeScript)",
  "cagri.olusturuldu": "سفارش ثبت شد: {kod}",

  "is.aktif": "فعال",
  "is.gecmis": "گذشته",
  "is.aktifYok": "درخواست فعالی ندارید.",
  "is.gecmisYok": "سفارش گذشته‌ای ندارید.",
  "asama.alindi": "درخواست دریافت شد",
  "asama.onaylandi": "استادکار پذیرفت",
  "asama.yolda": "در راه",
  "asama.kapida": "دم در",
  "asama.tamamlandi": "انجام شد",
  "is.varis": "زمان تقریبی رسیدن {saat}",
  "is.kalan": "{dk} دقیقه مانده",
  "is.randevu": "نوبت: {zaman}",
  "is.kapidaNot": "استادکار باید دم در باشد. پیش از باز کردن در، کدی را که می‌گوید بررسی کنید.",
  "is.kopyala": "کپی کد",
  "is.kopyalandi": "کد کپی شد",
  "is.qrGoster": "نمایش کد QR",
  "is.qrGizle": "پنهان کردن کد QR",
  "is.qrEtiket": "کد QR برای کد سفارش {kod}",
  "is.qrNot": "استادکار با اسکن این QR کار را ثبت می‌کند.",
  "is.fiyatDokumu": "ریز هزینه",
  "is.dogrulandi": "استادکار تأیید شد",
  "is.bitir": "کار تمام شد",
  "is.bitirNot": "پیش از پایان دادن به کار، کد استادکار دم در را بررسی کنید.",
  "is.iptalBaslik": "لغو درخواست",
  "is.iptalSoru": "دلیل لغو چیست؟",
  "iptal.vazgectim": "منصرف شدم",
  "iptal.gecikti": "استادکار دیر کرد",
  "iptal.baskasi": "استادکار دیگری پیدا کردم",
  "iptal.cozuldu": "مشکل خودبه‌خود حل شد",
  "is.iptalOnay": "لغو درخواست",
  "is.iptalEdildi": "درخواست لغو شد",
  "is.degerlendir": "امتیاز دهید",
  "is.degerlendirBaslik": "{usta} چطور بود؟",
  "is.yorumYer": "تجربه خود را در چند جمله بنویسید (اختیاری)",
  "is.gonder": "ارسال",
  "is.tesekkur": "از امتیاز شما سپاسگزاریم!",
  "is.puaniniz": "امتیاز شما",
  "is.puanSec": "{n} ستاره",
  "is.tekrar": "درخواست دوباره",
  "is.odeme": "پرداخت",
  "is.ustaArayacak": "استادکار با شماره {telefon} با شما تماس می‌گیرد.",

  "profil.toplamIs": "کل سفارش‌ها",
  "profil.tamamlananIs": "انجام‌شده",
  "profil.harcama": "هزینه‌شده",
  "profil.yorumlarim": "نظرهای من",
  "profil.favoriUstalar": "استادکاران مورد علاقه",
  "profil.favoriYok": "هنوز استادکار مورد علاقه‌ای ندارید. روی قلب کارت استادکار بزنید.",
  "profil.veri": "داده‌های من (KVKK)",
  "profil.disaAktar": "خروجی گرفتن از داده‌هایم (JSON)",
  "profil.sil": "حذف همه داده‌هایم در این دستگاه",
  "profil.silBaslik": "همه داده‌ها حذف شوند؟",
  "profil.silNot": "پروفایل، سفارش‌ها، علاقه‌مندی‌ها و نظرهای شما برای همیشه از این دستگاه حذف می‌شوند. این حق حذف شما طبق KVKK است.",
  "profil.silOnay": "بله، همه را حذف کن",
  "profil.silindi": "همه داده‌های شما حذف شد.",
  "profil.surum": "نسخه {surum} · هسته: {motor}",
  "motor.rust": "Rust (Tauri)",
  "motor.ts": "مرورگر (TypeScript)",

  "karsilama.atla": "رد شدن",
  "karsilama.ileri": "بعدی",
  "karsilama.adim1Baslik": "خرابی را انتخاب کن",
  "karsilama.adim1Metin": "نشت آب، برق، قفل، پکیج… با دو لمس بگو چه شده.",
  "karsilama.adim2Baslik": "استادکار در دسترس نزدیک را پیدا کن",
  "karsilama.adim2Metin": "پیش از درخواست، فاصله، زمان رسیدن، امتیاز و بازه قیمت را ببین.",
  "karsilama.adim3Baslik": "سفارش را با خیال راحت دنبال کن",
  "karsilama.adim3Metin": "کد استادکار پشت در را بررسی کن؛ اگر مطابقت نداشت در را باز نکن.",
  "karsilama.adim": "مرحله {n} از {toplam}",
  "genel.cevrimdisi": "آفلاین هستید. برنامه کار می‌کند چون داده‌هایتان روی همین دستگاه است.",

  "liste.konumDegistir": "تغییر موقعیت: {semt}",
  "liste.neOldu": "چه شده؟",
  "liste.acilAlt": "نزدیک‌ترین استادکار در دسترس، با یک لمس",
  "liste.enYakin": "{usta} · ~{dk} دقیقه",
  "liste.tarifEt": "خرابی را قدم‌به‌قدم توضیح بده",
  "liste.aramaOneri": "مشکل‌ها",
  "liste.tumUstalar": "همه استادکاران",
  "liste.filtrele": "فیلتر",
  "liste.siralaEtiket": "مرتب‌سازی: {ad}",
  "filtre.baslik": "فیلترها",
  "filtre.durum": "وضعیت",
  "filtre.mesafe": "فاصله",
  "filtre.mesafeKm": "≤ {n} کیلومتر",
  "filtre.puan": "حداقل امتیاز",
  "filtre.fiyat": "هزینه ایاب و ذهاب",
  "filtre.fiyatEnFazla": "≤ {tutar}",
  "filtre.dil": "زبانی که صحبت می‌کند",
  "filtre.tumu": "همه",
  "filtre.temizle": "پاک کردن",
  "filtre.goster": "نمایش {n} استادکار",
  "sirala.baslik": "مرتب‌سازی",
  "sirala.onerilenAciklama": "در دسترس بودن، فاصله، امتیاز، زمان پاسخ و زبان با هم",
  "sirala.yakinAciklama": "نزدیک‌ترین به شما اول",
  "sirala.puanAciklama": "بالاترین میانگین امتیاز اول",
  "sirala.fiyatAciklama": "کمترین هزینه ایاب و ذهاب اول",
  "neden.ac": "چرا پیشنهاد شد؟",
  "neden.baslik": "چرا این استادکار را پیشنهاد می‌کنیم؟",
  "neden.musait": "الان در دسترس است و می‌تواند فوراً بیاید",
  "neden.yakin": "در {km} کیلومتری شما",
  "neden.puan": "میانگین امتیاز {puan}",
  "neden.hizli": "به‌طور میانگین ظرف {dk} دقیقه پاسخ می‌دهد",
  "neden.dil": "{dil} صحبت می‌کند",
  "neden.fiyat": "هزینه ایاب و ذهاب کمتر از میانگین",
  "neden.not": "رتبه‌بندی فقط با همین اطلاعات و قواعد ثابت انجام می‌شود؛ تبلیغ پولی وجود ندارد.",
  "kart.simdiGelebilir": "الان می‌تواند بیاید · ~{dk} دقیقه",
  "kart.mesgulSonra": "مشغول · ~{dk} دقیقه دیگر آزاد",
  "kart.cikisDan": "ایاب و ذهاب {tutar}",
  "sihirbaz.alanSoru": "مشکل در چه زمینه‌ای است؟",
  "sihirbaz.sorunSoru": "کدام نزدیک‌تر است؟",
  "sihirbaz.aciliyetSoru": "چقدر فوری است؟",
  "sihirbaz.hemen": "همچنان ادامه دارد، باید فوراً بیاید",
  "sihirbaz.bugun": "امروز بیاید",
  "sihirbaz.randevu": "فوری نیست، نوبت کافی است",
  "sihirbaz.sonuc": "استادکاران مناسب شما",
  "sihirbaz.sonucYok": "الان استادکاری با این شرایط نیست. گزینه نوبت را امتحان کنید.",
  "sihirbaz.sec": "انتخاب این استادکار",
  "harita.listeyeDon": "بازگشت به فهرست",

  "detay.hemenVaris": "استادکار ممکن است حدود {dk} دقیقه دیگر دم در شما باشد.",
  "detay.acilAra": "اگر دود، آتش یا آسیب‌دیدگی هست، اول با ۱۱۲ تماس بگیرید",
  "detay.fotoGizlilik": "عکس فقط روی همین دستگاه می‌ماند و کوچک‌شده ذخیره می‌شود؛ به هیچ سروری فرستاده نمی‌شود.",
  "detay.fotoHata": "این فایل قابل استفاده نیست. عکسی کمتر از ۱۵ مگابایت انتخاب کنید.",
  "detay.fotoSec": "عکس بگیرید یا انتخاب کنید",
  "detay.varis": "رسیدن",
  "detay.yarin": "فردا",
  "cagri.adimUsta": "استادکار",
  "cagri.adimOnay": "تأیید",
  "cagri.degistir": "تغییر",
  "cagri.tekrarDene": "دوباره امتحان کنید",
  "fiyat.nasil": "چطور محاسبه شد؟",
  "fiyat.kuralCikis": "هزینه ایاب و ذهاب، دستمزد ثابت استادکار است.",
  "fiyat.kuralAcil": "برای درخواست‌های «همین الان» هزینه فوری {tutar} اضافه می‌شود.",
  "fiyat.kuralGece": "اگر بازدید بین ۲۲:۰۰ تا ۰۸:۰۰ باشد، ۲۵٪ هزینه ایاب و ذهاب اضافه می‌شود.",
  "fiyat.kuralPazar": "اگر بازدید یکشنبه باشد، ۱۵٪ هزینه ایاب و ذهاب اضافه می‌شود.",
  "fiyat.kuralIscilik": "دستمزد، بازه‌ای تقریبی بر اساس نوع مشکل است؛ مبلغ دقیق را استادکار در محل می‌گوید.",

  "is.guvenlikKodu": "کد امنیتی",
  "is.yanlisBaslik": "در را باز نکنید",
  "is.yanlisMetin": "این کد مربوط به سفارش شما نیست. از استادکار بخواهید دوباره بگوید؛ اگر همچنان شک دارید با ۱۱۲ تماس بگیرید.",
  "is.dogruBaslik": "کد درست است",
  "is.dogruMetin": "این همان استادکاری است که درخواست داده‌اید. می‌توانید در را باز کنید.",
  "is.ustaBilgi": "{kategori} · {semt}",
  "profil.hesabim": "حساب من",
  "profil.konum": "موقعیت",
  "profil.gorunum": "ظاهر",
  "profil.gizlilik": "حریم خصوصی",
  "profil.verilenPuan": "میانگین امتیاز شما",
  "profil.favoriBosBaslik": "هنوز استادکار مورد علاقه‌ای ندارید",
  "profil.favoriBosMetin": "استادکاران دلخواه را ذخیره کنید تا دفعه بعد سریع‌تر به آن‌ها برسید.",
  "profil.ustalaraGoz": "دیدن استادکاران",
};

export const sozlukler: Record<Dil, Record<Anahtar, string>> = { tr, en, ar, fa };
