// Arayüz metinleri — 4 dil (TR · EN · AR · FA). AR ve FA sağdan sola (RTL) gösterilir.
// Türkçe sözlük kaynak kabul edilir; diğer diller aynı anahtarların tamamını içermek zorundadır.
import type { Dil } from "../types/ustam";

const tr = {
  "uygulama.slogan": "Arıza senden, usta bizden.",

  "nav.ustalar": "Ustalar",
  "nav.cagri": "Çağrı",
  "nav.isEmirleri": "İş Emirlerim",
  "nav.profil": "Profil",

  "tema.degistir": "Tema: {ad} (değiştirmek için dokunun)",
  "tema.sistem": "Sistem",
  "tema.gunduz": "Gündüz",
  "tema.gece": "Gece",
  "genel.kapat": "Kapat",
  "dil.sec": "Dil seçin",

  "kategori.tesisat": "Tesisat",
  "kategori.elektrik": "Elektrik",
  "kategori.cilingir": "Çilingir",
  "kategori.kombi": "Kombi",
  "kategori.beyaz-esya": "Beyaz Eşya",

  "sorun.su-sizintisi": "Su sızıntısı",
  "sorun.tikali-gider": "Tıkalı gider",
  "sorun.musluk-ariza": "Musluk arızası",
  "sorun.sigorta-atiyor": "Sigorta sürekli atıyor",
  "sorun.priz-yanik": "Priz yanık kokuyor",
  "sorun.elektrik-yok": "Evde elektrik yok",
  "sorun.kapida-kaldim": "Kapıda kaldım",
  "sorun.kilit-degisimi": "Kilit değişimi",
  "sorun.anahtar-kirildi": "Anahtar kilitte kırıldı",
  "sorun.sicak-su-yok": "Sıcak su yok",
  "sorun.basinc-dusuk": "Kombi basınç düşürüyor",
  "sorun.petek-isinmiyor": "Petekler ısınmıyor",
  "sorun.camasir-makinesi": "Çamaşır makinesi su boşaltmıyor",
  "sorun.buzdolabi": "Buzdolabı soğutmuyor",
  "sorun.bulasik-makinesi": "Bulaşık makinesi çalışmıyor",

  "aciliyet.hemen": "Hemen",
  "aciliyet.bugun": "Bugün",
  "aciliyet.randevu": "Randevu",

  "liste.baslik": "Yakınındaki ustalar",
  "liste.arama": "Usta adı, uzmanlık veya semt ara",
  "liste.tumu": "Tümü",
  "liste.sadeceMusait": "Sadece müsait olanlar",
  "liste.sonuc": "{n} usta",
  "liste.bos": "Aramanıza uygun usta bulunamadı.",

  "kart.musait": "Şu an müsait",
  "kart.mesgul": "Meşgul",
  "kart.km": "{n} km",
  "kart.yorum": "{n} yorum",
  "kart.cikis": "Çıkış ücreti {tutar}",

  "detay.deneyim": "Deneyim",
  "detay.yil": "{n} yıl",
  "detay.tamamlanan": "Tamamlanan iş",
  "detay.bolge": "Bölge",
  "detay.sorunSec": "Sorununuz ne?",
  "detay.aciliyet": "Ne zaman gelsin?",
  "detay.saat": "Ziyaret saati",
  "detay.tarih": "Tarih",
  "detay.hemenNot": "Usta yaklaşık 30 dakika içinde kapınızda.",
  "detay.acilUcret": "+{tutar} acil servis ücreti",
  "detay.bugunSaatYok": "Bugün için boş saat kalmadı, lütfen randevu seçin.",
  "detay.adres": "Adres notu",
  "detay.adresOrnek": "Kat, daire no, zil adı…",
  "detay.ustayaIletilen": "Ustaya Türkçe iletilecek:",
  "detay.mesgulUyari": "Bu usta şu an meşgul; yalnızca randevu alabilirsiniz.",
  "detay.cagir": "Ustayı çağır · {tutar}",
  "detay.cagirKisa": "Ustayı çağır",

  "cagri.baslik": "Çağrı özeti",
  "cagri.bos": "Henüz bir çağrı oluşturmadınız.",
  "cagri.ustaSec": "Bir usta seçin →",
  "cagri.usta": "Usta",
  "cagri.sorun": "Sorun",
  "cagri.zaman": "Zaman",
  "cagri.adres": "Adres notu",
  "cagri.cikis": "Çıkış ücreti",
  "cagri.acil": "Acil servis ücreti",
  "cagri.toplam": "Tahmini toplam",
  "cagri.gece": "Gece ek ücreti (22:00–08:00)",
  "cagri.pazar": "Pazar ek ücreti",
  "cagri.iscilik": "Tahmini işçilik",
  "cagri.rust": "Döküm, uygulamanın Rust çekirdeğinde hesaplanır.",
  "cagri.not": "Parça ve işçilik ücreti usta tarafından yerinde belirlenir.",
  "cagri.onayla": "Çağrıyı onayla",
  "cagri.isleniyor": "İş emri kodu üretiliyor…",
  "cagri.vazgec": "Vazgeç",
  "cagri.hata": "Kod üretilemedi:",

  "is.baslik": "İş Emirlerim",
  "is.bos": "Henüz iş emriniz yok.",
  "is.kod": "İş emri kodu",
  "is.kodNot": "Usta kapıya geldiğinde bu kodu söylemesini isteyin.",
  "is.tamamla": "Tamamlandı",
  "is.iptal": "İptal et",
  "is.dogrulaBaslik": "Kapıdaki ustayı doğrula",
  "is.dogrulaYer": "Ustanın söylediği kod",
  "is.dogrulaBtn": "Doğrula",
  "is.dogru": "Kod doğru — bu, sizin çağırdığınız usta.",
  "is.yanlis": "Bu kod iş emirlerinizde yok. Kapıyı açmayın!",
  "is.formatHatali": "Kod biçimi hatalı (ör. UST-ELK-1210-K7QM).",
  "is.kontrolHatali": "Kod yanlış yazılmış olabilir: kontrol karakteri tutmuyor. Ustadan kodu tekrar söylemesini isteyin.",

  "durum.bekliyor": "Bekliyor",
  "durum.yolda": "Usta yolda",
  "durum.tamamlandi": "Tamamlandı",
  "durum.iptal": "İptal edildi",

  "profil.baslik": "Profil",
  "profil.misafir": "Misafir kullanıcı",
  "profil.isSayisi": "{n} iş emriniz var",
  "profil.ad": "Ad Soyad",
  "profil.telefon": "Telefon",
  "profil.adres": "Adres",
  "profil.kaydet": "Kaydet",
  "profil.kaydedildi": "Kaydedildi ✓",
  "profil.ayarlar": "Ayarlar",
  "profil.dil": "Uygulama dili",
  "profil.tema": "Tema",
  "profil.bilgi": "Bilgi ve yasal",

  "sayfa.hakkinda": "Hakkında",
  "sayfa.iletisim": "İletişim",
  "sayfa.kosullar": "Kullanım Koşulları",
  "sayfa.gizlilik": "Gizlilik Politikası",

  "iletisim.aciklama": "Soru, öneri veya usta başvurusu için bize yazın. Genellikle 1 iş günü içinde yanıt veririz.",
  "iletisim.ad": "Adınız",
  "iletisim.eposta": "E-posta",
  "iletisim.konu": "Konu",
  "iletisim.mesaj": "Mesajınız",
  "iletisim.ipucu": "Tüm alanları doldurun; mesaj en az 10 karakter olmalı.",
  "iletisim.gonder": "Gönder",
  "iletisim.gonderiliyor": "Gönderiliyor…",
  "iletisim.basarili": "Mesajınız iletildi. Teşekkür ederiz!",
  "konu.genel": "Genel soru",
  "konu.usta": "Usta olarak katılmak istiyorum",
  "konu.sikayet": "Şikayet",
  "konu.oneri": "Öneri",

  "liste.merhaba": "Merhaba",
  "liste.merhabaAd": "Merhaba, {ad}",
  "liste.soru": "Ne tamir edelim?",
  "liste.konumSec": "Semtinizi seçin",
  "liste.acilBaslik": "Acil mi? En yakın müsait usta",
  "liste.acilYok": "Şu an müsait usta yok",
  "liste.aktifYolda": "{usta} yolda · yaklaşık {dk} dk",
  "liste.aktifRandevu": "{usta} · randevu {zaman}",
  "liste.favoriler": "Favoriler",
  "liste.dilimiKonusan": "Türkçe konuşan",
  "liste.sirala": "Sırala",
  "liste.gorunum": "Görünüm",
  "liste.liste": "Liste",
  "liste.harita": "Harita",
  "liste.filtreTemizle": "Filtreleri temizle",
  "sirala.onerilen": "Önerilen",
  "sirala.yakin": "En yakın",
  "sirala.puan": "En yüksek puan",
  "sirala.fiyat": "En uygun fiyat",

  "kart.kapali": "Kapalı · {saat} açılır",
  "kart.dk": "~{dk} dk",
  "kart.favoriEkle": "Favorilere ekle",
  "kart.favoriCikar": "Favorilerden çıkar",
  "kart.favoriEklendi": "{ad} favorilere eklendi",
  "kart.favoriCikarildi": "{ad} favorilerden çıkarıldı",

  "rozet.dogrulanmis": "Kimliği doğrulandı",
  "rozet.sigortali": "Sigortalı işçilik",
  "rozet.7-24": "7/24 hizmet",
  "rozet.hizli-yanit": "Hızlı yanıt",

  "detay.geri": "Geri",
  "detay.yanit": "Yanıt süresi",
  "detay.mesafe": "Uzaklık",
  "detay.calisma": "Çalışma saatleri",
  "detay.724": "7 gün 24 saat",
  "detay.diller": "Konuştuğu diller",
  "detay.dilinizi": "Sizin dilinizi konuşuyor",
  "detay.sure": "~{dk} dk iş",
  "detay.guvenlik": "Usta gelene kadar",
  "detay.foto": "Arızanın fotoğrafını ekleyin (isteğe bağlı)",
  "detay.fotoNot": "Fotoğraf, ustanın doğru parçayla gelmesine yardım eder.",
  "detay.fotoKaldir": "Fotoğrafı kaldır",
  "detay.yorumlar": "Yorumlar",
  "detay.yorumSayisi": "{n} değerlendirme",
  "detay.tumYorumlar": "Tüm yorumları göster",
  "detay.sizinYorumunuz": "Sizin yorumunuz",
  "detay.kapaliUyari": "Bu usta şu an kapalı ({saat} açılır); bugün daha sonrası veya randevu seçebilirsiniz.",
  "detay.bulunamadi": "Usta bulunamadı.",

  "ipucu.su-sizintisi": "Ana su vanasını kapatın; sızan suyu prizlerden ve elektrikli cihazlardan uzak tutun.",
  "ipucu.tikali-gider": "Kimyasal açıcı dökmeyin; usta gelene kadar o gideri kullanmayın.",
  "ipucu.musluk-ariza": "Lavabonun altındaki ara musluğu kapatın.",
  "ipucu.sigorta-atiyor": "Son taktığınız cihazı prizden çekin; sigortayı tekrar tekrar kaldırmayın.",
  "ipucu.priz-yanik": "O hattın sigortasını kapatın, prize dokunmayın. Duman veya alev varsa 112'yi arayın.",
  "ipucu.elektrik-yok": "Komşularda da elektrik yoksa genel kesinti olabilir; buzdolabının kapağını açmayın.",
  "ipucu.kapida-kaldim": "Kapıyı zorlamayın; kimliğinizi yanınızda bulundurun, usta ev sahipliğini soracaktır.",
  "ipucu.kilit-degisimi": "Kullandığınız kilit tipinin fotoğrafını ekleyin; usta uygun silindiri getirsin.",
  "ipucu.anahtar-kirildi": "Kırık parçayı kendiniz çıkarmaya çalışmayın; kilit daha çok zarar görebilir.",
  "ipucu.sicak-su-yok": "Kombinin ekranındaki hata kodunu not edin ve kombiyi kapatıp açmayı bir kez deneyin.",
  "ipucu.basinc-dusuk": "Basınç göstergesinin fotoğrafını çekin; kombiyi kapatın.",
  "ipucu.petek-isinmiyor": "Peteklerin vanalarının açık olduğundan emin olun.",
  "ipucu.camasir-makinesi": "Makineyi kapatıp fişini çekin; kapağı zorlamayın.",
  "ipucu.buzdolabi": "Kapağı olabildiğince kapalı tutun; bozulabilecek gıdaları serin bir yere alın.",
  "ipucu.bulasik-makinesi": "Makinenin fişini çekin ve su musluğunu kapatın.",

  "harita.etiket": "İstanbul'daki ustaların haritası",
  "harita.sen": "Siz",
  "harita.profil": "Profili gör",
  "harita.avrupa": "Avrupa Yakası",
  "harita.asya": "Anadolu Yakası",

  "karsilama.baslik": "Ustam'a hoş geldiniz",
  "karsilama.alt": "Evdeki arızaya en yakın müsait ustayı, kendi dilinizde çağırın.",
  "karsilama.dilSec": "Dilinizi seçin",
  "karsilama.semtSec": "Hangi semttesiniz?",
  "karsilama.semtNot": "En yakın ustaları göstermek için kullanılır; cihazınızdan çıkmaz.",
  "karsilama.devam": "Devam",
  "karsilama.basla": "Başla",
  "karsilama.ozellik1": "Yakındaki müsait ustalar ve varış süresi",
  "karsilama.ozellik2": "Sorununuzu kendi dilinizde anlatın",
  "karsilama.ozellik3": "Kapıda iş emri koduyla güvenli doğrulama",
} as const;

export type Anahtar = keyof typeof tr;

const en: Record<Anahtar, string> = {
  "uygulama.slogan": "Your breakdown, our pro.",

  "nav.ustalar": "Pros",
  "nav.cagri": "Request",
  "nav.isEmirleri": "My Jobs",
  "nav.profil": "Profile",

  "tema.degistir": "Theme: {ad} (tap to change)",
  "tema.sistem": "System",
  "tema.gunduz": "Light",
  "tema.gece": "Dark",
  "genel.kapat": "Close",
  "dil.sec": "Choose language",

  "kategori.tesisat": "Plumbing",
  "kategori.elektrik": "Electrical",
  "kategori.cilingir": "Locksmith",
  "kategori.kombi": "Boiler",
  "kategori.beyaz-esya": "Appliances",

  "sorun.su-sizintisi": "Water leak",
  "sorun.tikali-gider": "Clogged drain",
  "sorun.musluk-ariza": "Broken faucet",
  "sorun.sigorta-atiyor": "Fuse keeps tripping",
  "sorun.priz-yanik": "Outlet smells burnt",
  "sorun.elektrik-yok": "No power at home",
  "sorun.kapida-kaldim": "Locked out",
  "sorun.kilit-degisimi": "Lock replacement",
  "sorun.anahtar-kirildi": "Key broke in the lock",
  "sorun.sicak-su-yok": "No hot water",
  "sorun.basinc-dusuk": "Boiler losing pressure",
  "sorun.petek-isinmiyor": "Radiators not heating",
  "sorun.camasir-makinesi": "Washing machine won't drain",
  "sorun.buzdolabi": "Fridge not cooling",
  "sorun.bulasik-makinesi": "Dishwasher not working",

  "aciliyet.hemen": "Right now",
  "aciliyet.bugun": "Today",
  "aciliyet.randevu": "Schedule",

  "liste.baslik": "Pros near you",
  "liste.arama": "Search name, trade or district",
  "liste.tumu": "All",
  "liste.sadeceMusait": "Available only",
  "liste.sonuc": "{n} pros",
  "liste.bos": "No pros match your search.",

  "kart.musait": "Available now",
  "kart.mesgul": "Busy",
  "kart.km": "{n} km",
  "kart.yorum": "{n} reviews",
  "kart.cikis": "Call-out fee {tutar}",

  "detay.deneyim": "Experience",
  "detay.yil": "{n} yrs",
  "detay.tamamlanan": "Jobs done",
  "detay.bolge": "Area",
  "detay.sorunSec": "What's the problem?",
  "detay.aciliyet": "When should they come?",
  "detay.saat": "Visit time",
  "detay.tarih": "Date",
  "detay.hemenNot": "The pro will be at your door in about 30 minutes.",
  "detay.acilUcret": "+{tutar} emergency fee",
  "detay.bugunSaatYok": "No slots left today, please schedule a visit.",
  "detay.adres": "Address note",
  "detay.adresOrnek": "Floor, flat no, doorbell name…",
  "detay.ustayaIletilen": "Sent to the pro in Turkish:",
  "detay.mesgulUyari": "This pro is busy right now; you can only schedule a visit.",
  "detay.cagir": "Call the pro · {tutar}",
  "detay.cagirKisa": "Call the pro",

  "cagri.baslik": "Request summary",
  "cagri.bos": "You haven't created a request yet.",
  "cagri.ustaSec": "Choose a pro →",
  "cagri.usta": "Pro",
  "cagri.sorun": "Problem",
  "cagri.zaman": "Time",
  "cagri.adres": "Address note",
  "cagri.cikis": "Call-out fee",
  "cagri.acil": "Emergency fee",
  "cagri.toplam": "Estimated total",
  "cagri.gece": "Night surcharge (22:00–08:00)",
  "cagri.pazar": "Sunday surcharge",
  "cagri.iscilik": "Estimated labour",
  "cagri.rust": "The breakdown is calculated by the app's Rust core.",
  "cagri.not": "Parts and labour are priced on site by the pro.",
  "cagri.onayla": "Confirm request",
  "cagri.isleniyor": "Generating job code…",
  "cagri.vazgec": "Cancel",
  "cagri.hata": "Could not generate code:",

  "is.baslik": "My Jobs",
  "is.bos": "You have no jobs yet.",
  "is.kod": "Job code",
  "is.kodNot": "Ask the pro to tell you this code at the door.",
  "is.tamamla": "Mark done",
  "is.iptal": "Cancel",
  "is.dogrulaBaslik": "Verify the pro at your door",
  "is.dogrulaYer": "Code the pro tells you",
  "is.dogrulaBtn": "Verify",
  "is.dogru": "Code is correct — this is the pro you called.",
  "is.yanlis": "This code is not in your jobs. Do not open the door!",
  "is.formatHatali": "Invalid code format (e.g. UST-ELK-1210-K7QM).",
  "is.kontrolHatali": "The code may be mistyped: the check character does not match. Ask the pro to repeat it.",

  "durum.bekliyor": "Scheduled",
  "durum.yolda": "On the way",
  "durum.tamamlandi": "Done",
  "durum.iptal": "Cancelled",

  "profil.baslik": "Profile",
  "profil.misafir": "Guest user",
  "profil.isSayisi": "You have {n} jobs",
  "profil.ad": "Full name",
  "profil.telefon": "Phone",
  "profil.adres": "Address",
  "profil.kaydet": "Save",
  "profil.kaydedildi": "Saved ✓",
  "profil.ayarlar": "Settings",
  "profil.dil": "App language",
  "profil.tema": "Theme",
  "profil.bilgi": "Info & legal",

  "sayfa.hakkinda": "About",
  "sayfa.iletisim": "Contact",
  "sayfa.kosullar": "Terms of Use",
  "sayfa.gizlilik": "Privacy Policy",

  "iletisim.aciklama": "Write to us with questions, ideas or to join as a pro. We usually reply within 1 business day.",
  "iletisim.ad": "Your name",
  "iletisim.eposta": "Email",
  "iletisim.konu": "Subject",
  "iletisim.mesaj": "Your message",
  "iletisim.ipucu": "Fill in all fields; the message must be at least 10 characters.",
  "iletisim.gonder": "Send",
  "iletisim.gonderiliyor": "Sending…",
  "iletisim.basarili": "Your message has been sent. Thank you!",
  "konu.genel": "General question",
  "konu.usta": "I want to join as a pro",
  "konu.sikayet": "Complaint",
  "konu.oneri": "Suggestion",

  "liste.merhaba": "Hello",
  "liste.merhabaAd": "Hello, {ad}",
  "liste.soru": "What needs fixing?",
  "liste.konumSec": "Choose your district",
  "liste.acilBaslik": "Urgent? Nearest available pro",
  "liste.acilYok": "No pro available right now",
  "liste.aktifYolda": "{usta} is on the way · about {dk} min",
  "liste.aktifRandevu": "{usta} · appointment {zaman}",
  "liste.favoriler": "Favourites",
  "liste.dilimiKonusan": "Speaks English",
  "liste.sirala": "Sort",
  "liste.gorunum": "View",
  "liste.liste": "List",
  "liste.harita": "Map",
  "liste.filtreTemizle": "Clear filters",
  "sirala.onerilen": "Recommended",
  "sirala.yakin": "Nearest",
  "sirala.puan": "Top rated",
  "sirala.fiyat": "Lowest price",

  "kart.kapali": "Closed · opens {saat}",
  "kart.dk": "~{dk} min",
  "kart.favoriEkle": "Add to favourites",
  "kart.favoriCikar": "Remove from favourites",
  "kart.favoriEklendi": "{ad} added to favourites",
  "kart.favoriCikarildi": "{ad} removed from favourites",

  "rozet.dogrulanmis": "ID verified",
  "rozet.sigortali": "Insured work",
  "rozet.7-24": "24/7 service",
  "rozet.hizli-yanit": "Fast response",

  "detay.geri": "Back",
  "detay.yanit": "Response time",
  "detay.mesafe": "Distance",
  "detay.calisma": "Working hours",
  "detay.724": "24 hours, 7 days",
  "detay.diller": "Languages spoken",
  "detay.dilinizi": "Speaks your language",
  "detay.sure": "~{dk} min job",
  "detay.guvenlik": "Until the pro arrives",
  "detay.foto": "Add a photo of the problem (optional)",
  "detay.fotoNot": "A photo helps the pro bring the right part.",
  "detay.fotoKaldir": "Remove photo",
  "detay.yorumlar": "Reviews",
  "detay.yorumSayisi": "{n} ratings",
  "detay.tumYorumlar": "Show all reviews",
  "detay.sizinYorumunuz": "Your review",
  "detay.kapaliUyari": "This pro is closed right now (opens {saat}); you can choose later today or schedule a visit.",
  "detay.bulunamadi": "Pro not found.",

  "ipucu.su-sizintisi": "Turn off the main water valve; keep leaking water away from sockets and appliances.",
  "ipucu.tikali-gider": "Do not pour chemical drain openers; do not use that drain until the pro arrives.",
  "ipucu.musluk-ariza": "Close the shut-off valve under the sink.",
  "ipucu.sigorta-atiyor": "Unplug the last device you connected; do not keep resetting the fuse.",
  "ipucu.priz-yanik": "Switch off that circuit's fuse and do not touch the socket. If there is smoke or fire, call 112.",
  "ipucu.elektrik-yok": "If neighbours have no power either, it may be a general outage; keep the fridge door closed.",
  "ipucu.kapida-kaldim": "Do not force the door; keep your ID with you, the pro will ask for proof of residence.",
  "ipucu.kilit-degisimi": "Add a photo of your lock so the pro brings a matching cylinder.",
  "ipucu.anahtar-kirildi": "Do not try to pull out the broken piece yourself; it can damage the lock further.",
  "ipucu.sicak-su-yok": "Note the error code on the boiler display and try switching it off and on once.",
  "ipucu.basinc-dusuk": "Take a photo of the pressure gauge and turn the boiler off.",
  "ipucu.petek-isinmiyor": "Make sure the radiator valves are open.",
  "ipucu.camasir-makinesi": "Switch the machine off and unplug it; do not force the door.",
  "ipucu.buzdolabi": "Keep the door closed as much as possible; move perishable food somewhere cool.",
  "ipucu.bulasik-makinesi": "Unplug the machine and close its water tap.",

  "harita.etiket": "Map of pros in Istanbul",
  "harita.sen": "You",
  "harita.profil": "View profile",
  "harita.avrupa": "European side",
  "harita.asya": "Asian side",

  "karsilama.baslik": "Welcome to Ustam",
  "karsilama.alt": "Call the nearest available pro for any breakdown at home, in your own language.",
  "karsilama.dilSec": "Choose your language",
  "karsilama.semtSec": "Which district are you in?",
  "karsilama.semtNot": "Used to show the nearest pros; it never leaves your device.",
  "karsilama.devam": "Continue",
  "karsilama.basla": "Get started",
  "karsilama.ozellik1": "Nearby available pros and arrival time",
  "karsilama.ozellik2": "Describe your problem in your own language",
  "karsilama.ozellik3": "Safe check at the door with a job code",
};

const ar: Record<Anahtar, string> = {
  "uygulama.slogan": "العطل عليك، والفنّي علينا.",

  "nav.ustalar": "الفنّيون",
  "nav.cagri": "الطلب",
  "nav.isEmirleri": "طلباتي",
  "nav.profil": "حسابي",

  "tema.degistir": "المظهر: {ad} (اضغط للتغيير)",
  "tema.sistem": "النظام",
  "tema.gunduz": "فاتح",
  "tema.gece": "داكن",
  "genel.kapat": "إغلاق",
  "dil.sec": "اختر اللغة",

  "kategori.tesisat": "سباكة",
  "kategori.elektrik": "كهرباء",
  "kategori.cilingir": "أقفال ومفاتيح",
  "kategori.kombi": "غلاية التدفئة",
  "kategori.beyaz-esya": "أجهزة منزلية",

  "sorun.su-sizintisi": "تسرّب مياه",
  "sorun.tikali-gider": "انسداد المصرف",
  "sorun.musluk-ariza": "عطل في الحنفية",
  "sorun.sigorta-atiyor": "القاطع الكهربائي يفصل باستمرار",
  "sorun.priz-yanik": "رائحة احتراق من المقبس",
  "sorun.elektrik-yok": "لا توجد كهرباء في المنزل",
  "sorun.kapida-kaldim": "أنا عالق خارج الباب",
  "sorun.kilit-degisimi": "تغيير القفل",
  "sorun.anahtar-kirildi": "انكسر المفتاح داخل القفل",
  "sorun.sicak-su-yok": "لا يوجد ماء ساخن",
  "sorun.basinc-dusuk": "ضغط الغلاية ينخفض",
  "sorun.petek-isinmiyor": "المشعات لا تسخن",
  "sorun.camasir-makinesi": "الغسالة لا تصرّف الماء",
  "sorun.buzdolabi": "الثلاجة لا تبرّد",
  "sorun.bulasik-makinesi": "غسالة الصحون لا تعمل",

  "aciliyet.hemen": "فورًا",
  "aciliyet.bugun": "اليوم",
  "aciliyet.randevu": "موعد لاحق",

  "liste.baslik": "فنّيون بالقرب منك",
  "liste.arama": "ابحث بالاسم أو الاختصاص أو الحي",
  "liste.tumu": "الكل",
  "liste.sadeceMusait": "المتاحون فقط",
  "liste.sonuc": "{n} فنّي",
  "liste.bos": "لا يوجد فنّي يطابق بحثك.",

  "kart.musait": "متاح الآن",
  "kart.mesgul": "مشغول",
  "kart.km": "{n} كم",
  "kart.yorum": "{n} تقييم",
  "kart.cikis": "رسوم الزيارة {tutar}",

  "detay.deneyim": "الخبرة",
  "detay.yil": "{n} سنة",
  "detay.tamamlanan": "أعمال منجزة",
  "detay.bolge": "المنطقة",
  "detay.sorunSec": "ما هي المشكلة؟",
  "detay.aciliyet": "متى يأتي الفنّي؟",
  "detay.saat": "وقت الزيارة",
  "detay.tarih": "التاريخ",
  "detay.hemenNot": "سيصل الفنّي إلى بابك خلال 30 دقيقة تقريبًا.",
  "detay.acilUcret": "+{tutar} رسوم الطوارئ",
  "detay.bugunSaatYok": "لا توجد مواعيد متبقية اليوم، يرجى اختيار موعد لاحق.",
  "detay.adres": "ملاحظة العنوان",
  "detay.adresOrnek": "الطابق، رقم الشقة، اسم الجرس…",
  "detay.ustayaIletilen": "سيُرسل إلى الفنّي بالتركية:",
  "detay.mesgulUyari": "هذا الفنّي مشغول الآن؛ يمكنك حجز موعد لاحق فقط.",
  "detay.cagir": "اطلب الفنّي · {tutar}",
  "detay.cagirKisa": "اطلب الفنّي",

  "cagri.baslik": "ملخّص الطلب",
  "cagri.bos": "لم تُنشئ أي طلب بعد.",
  "cagri.ustaSec": "← اختر فنّيًا",
  "cagri.usta": "الفنّي",
  "cagri.sorun": "المشكلة",
  "cagri.zaman": "الوقت",
  "cagri.adres": "ملاحظة العنوان",
  "cagri.cikis": "رسوم الزيارة",
  "cagri.acil": "رسوم الطوارئ",
  "cagri.toplam": "الإجمالي التقديري",
  "cagri.gece": "رسوم إضافية ليلية (22:00–08:00)",
  "cagri.pazar": "رسوم إضافية يوم الأحد",
  "cagri.iscilik": "تكلفة العمل التقديرية",
  "cagri.rust": "يُحسب هذا التفصيل في نواة Rust الخاصة بالتطبيق.",
  "cagri.not": "يحدّد الفنّي تكلفة القطع والعمل في الموقع.",
  "cagri.onayla": "تأكيد الطلب",
  "cagri.isleniyor": "جارٍ إنشاء رمز الطلب…",
  "cagri.vazgec": "إلغاء",
  "cagri.hata": "تعذّر إنشاء الرمز:",

  "is.baslik": "طلباتي",
  "is.bos": "لا توجد لديك طلبات بعد.",
  "is.kod": "رمز الطلب",
  "is.kodNot": "اطلب من الفنّي أن يذكر هذا الرمز عند الباب.",
  "is.tamamla": "تمّ الإنجاز",
  "is.iptal": "إلغاء",
  "is.dogrulaBaslik": "تحقّق من الفنّي عند الباب",
  "is.dogrulaYer": "الرمز الذي يذكره الفنّي",
  "is.dogrulaBtn": "تحقّق",
  "is.dogru": "الرمز صحيح — هذا هو الفنّي الذي طلبته.",
  "is.yanlis": "هذا الرمز غير موجود في طلباتك. لا تفتح الباب!",
  "is.formatHatali": "صيغة الرمز غير صحيحة (مثال: UST-ELK-1210-K7QM).",
  "is.kontrolHatali": "ربما كُتب الرمز بشكل خاطئ: حرف التحقق لا يطابق. اطلب من الفنّي تكراره.",

  "durum.bekliyor": "بانتظار الموعد",
  "durum.yolda": "الفنّي في الطريق",
  "durum.tamamlandi": "منجز",
  "durum.iptal": "ملغى",

  "profil.baslik": "حسابي",
  "profil.misafir": "مستخدم زائر",
  "profil.isSayisi": "لديك {n} طلبات",
  "profil.ad": "الاسم الكامل",
  "profil.telefon": "الهاتف",
  "profil.adres": "العنوان",
  "profil.kaydet": "حفظ",
  "profil.kaydedildi": "تمّ الحفظ ✓",
  "profil.ayarlar": "الإعدادات",
  "profil.dil": "لغة التطبيق",
  "profil.tema": "المظهر",
  "profil.bilgi": "معلومات وشروط",

  "sayfa.hakkinda": "حول التطبيق",
  "sayfa.iletisim": "اتصل بنا",
  "sayfa.kosullar": "شروط الاستخدام",
  "sayfa.gizlilik": "سياسة الخصوصية",

  "iletisim.aciklama": "راسلنا لأي سؤال أو اقتراح أو للانضمام كفنّي. نرد عادةً خلال يوم عمل واحد.",
  "iletisim.ad": "اسمك",
  "iletisim.eposta": "البريد الإلكتروني",
  "iletisim.konu": "الموضوع",
  "iletisim.mesaj": "رسالتك",
  "iletisim.ipucu": "املأ جميع الحقول؛ يجب ألا تقل الرسالة عن 10 أحرف.",
  "iletisim.gonder": "إرسال",
  "iletisim.gonderiliyor": "جارٍ الإرسال…",
  "iletisim.basarili": "تم إرسال رسالتك. شكرًا لك!",
  "konu.genel": "سؤال عام",
  "konu.usta": "أريد الانضمام كفنّي",
  "konu.sikayet": "شكوى",
  "konu.oneri": "اقتراح",

  "liste.merhaba": "مرحبًا",
  "liste.merhabaAd": "مرحبًا، {ad}",
  "liste.soru": "ماذا نصلح اليوم؟",
  "liste.konumSec": "اختر حيّك",
  "liste.acilBaslik": "حالة طارئة؟ أقرب فنّي متاح",
  "liste.acilYok": "لا يوجد فنّي متاح الآن",
  "liste.aktifYolda": "{usta} في الطريق · حوالي {dk} دقيقة",
  "liste.aktifRandevu": "{usta} · موعد {zaman}",
  "liste.favoriler": "المفضّلة",
  "liste.dilimiKonusan": "يتحدث العربية",
  "liste.sirala": "ترتيب",
  "liste.gorunum": "طريقة العرض",
  "liste.liste": "قائمة",
  "liste.harita": "خريطة",
  "liste.filtreTemizle": "مسح الفلاتر",
  "sirala.onerilen": "المقترح",
  "sirala.yakin": "الأقرب",
  "sirala.puan": "الأعلى تقييمًا",
  "sirala.fiyat": "الأقل سعرًا",

  "kart.kapali": "مغلق · يفتح {saat}",
  "kart.dk": "~{dk} د",
  "kart.favoriEkle": "إضافة إلى المفضّلة",
  "kart.favoriCikar": "إزالة من المفضّلة",
  "kart.favoriEklendi": "أُضيف {ad} إلى المفضّلة",
  "kart.favoriCikarildi": "أُزيل {ad} من المفضّلة",

  "rozet.dogrulanmis": "هوية موثّقة",
  "rozet.sigortali": "عمل مؤمَّن",
  "rozet.7-24": "خدمة 24/7",
  "rozet.hizli-yanit": "استجابة سريعة",

  "detay.geri": "رجوع",
  "detay.yanit": "زمن الاستجابة",
  "detay.mesafe": "المسافة",
  "detay.calisma": "ساعات العمل",
  "detay.724": "24 ساعة، 7 أيام",
  "detay.diller": "اللغات التي يتحدثها",
  "detay.dilinizi": "يتحدث لغتك",
  "detay.sure": "عمل لمدة ~{dk} دقيقة",
  "detay.guvenlik": "إلى أن يصل الفنّي",
  "detay.foto": "أضف صورة للعطل (اختياري)",
  "detay.fotoNot": "تساعد الصورة الفنّي على إحضار القطعة المناسبة.",
  "detay.fotoKaldir": "إزالة الصورة",
  "detay.yorumlar": "التقييمات",
  "detay.yorumSayisi": "{n} تقييم",
  "detay.tumYorumlar": "عرض كل التقييمات",
  "detay.sizinYorumunuz": "تقييمك",
  "detay.kapaliUyari": "هذا الفنّي مغلق الآن (يفتح {saat})؛ يمكنك اختيار وقت لاحق اليوم أو حجز موعد.",
  "detay.bulunamadi": "لم يتم العثور على الفنّي.",

  "ipucu.su-sizintisi": "أغلق محبس المياه الرئيسي، وأبعد المياه المتسرّبة عن المقابس والأجهزة الكهربائية.",
  "ipucu.tikali-gider": "لا تسكب مواد كيميائية لفتح الانسداد، ولا تستخدم هذا المصرف حتى يصل الفنّي.",
  "ipucu.musluk-ariza": "أغلق المحبس الفرعي تحت المغسلة.",
  "ipucu.sigorta-atiyor": "افصل آخر جهاز وصلته، ولا تُعِد رفع القاطع مرارًا.",
  "ipucu.priz-yanik": "افصل قاطع هذا الخط ولا تلمس المقبس. إن كان هناك دخان أو نار فاتصل بـ 112.",
  "ipucu.elektrik-yok": "إن لم تكن الكهرباء عند الجيران أيضًا فقد يكون انقطاعًا عامًا؛ لا تفتح باب الثلاجة.",
  "ipucu.kapida-kaldim": "لا تحاول كسر الباب؛ احتفظ بهويتك معك، فالفنّي سيطلب ما يثبت سكنك.",
  "ipucu.kilit-degisimi": "أضف صورة لنوع القفل كي يحضر الفنّي الأسطوانة المناسبة.",
  "ipucu.anahtar-kirildi": "لا تحاول إخراج القطعة المكسورة بنفسك؛ قد يتضرر القفل أكثر.",
  "ipucu.sicak-su-yok": "دوّن رمز الخطأ الظاهر على شاشة الغلاية، وجرّب إطفاءها وتشغيلها مرة واحدة.",
  "ipucu.basinc-dusuk": "التقط صورة لمؤشر الضغط وأطفئ الغلاية.",
  "ipucu.petek-isinmiyor": "تأكد من أن صمامات المشعات مفتوحة.",
  "ipucu.camasir-makinesi": "أطفئ الغسالة وافصل قابسها، ولا تفتح الباب بالقوة.",
  "ipucu.buzdolabi": "أبقِ الباب مغلقًا قدر الإمكان، وانقل الأطعمة القابلة للتلف إلى مكان بارد.",
  "ipucu.bulasik-makinesi": "افصل قابس الجهاز وأغلق صنبور المياه الخاص به.",

  "harita.etiket": "خريطة الفنّيين في إسطنبول",
  "harita.sen": "أنت",
  "harita.profil": "عرض الملف",
  "harita.avrupa": "الجانب الأوروبي",
  "harita.asya": "الجانب الآسيوي",

  "karsilama.baslik": "مرحبًا بك في Ustam",
  "karsilama.alt": "اطلب أقرب فنّي متاح لأي عطل في منزلك، وبلغتك.",
  "karsilama.dilSec": "اختر لغتك",
  "karsilama.semtSec": "في أي حيّ تسكن؟",
  "karsilama.semtNot": "يُستخدم لعرض أقرب الفنّيين، ولا يغادر جهازك.",
  "karsilama.devam": "متابعة",
  "karsilama.basla": "ابدأ",
  "karsilama.ozellik1": "فنّيون متاحون بالقرب منك مع وقت الوصول",
  "karsilama.ozellik2": "صف مشكلتك بلغتك",
  "karsilama.ozellik3": "تحقّق آمن عند الباب برمز الطلب",
};

const fa: Record<Anahtar, string> = {
  "uygulama.slogan": "خرابی با شما، استادکار با ما.",

  "nav.ustalar": "استادکاران",
  "nav.cagri": "درخواست",
  "nav.isEmirleri": "سفارش‌های من",
  "nav.profil": "پروفایل",

  "tema.degistir": "پوسته: {ad} (برای تغییر لمس کنید)",
  "tema.sistem": "سیستم",
  "tema.gunduz": "روشن",
  "tema.gece": "تاریک",
  "genel.kapat": "بستن",
  "dil.sec": "انتخاب زبان",

  "kategori.tesisat": "لوله‌کشی",
  "kategori.elektrik": "برق‌کاری",
  "kategori.cilingir": "کلیدسازی",
  "kategori.kombi": "پکیج",
  "kategori.beyaz-esya": "لوازم خانگی",

  "sorun.su-sizintisi": "نشت آب",
  "sorun.tikali-gider": "گرفتگی فاضلاب",
  "sorun.musluk-ariza": "خرابی شیر آب",
  "sorun.sigorta-atiyor": "فیوز مدام می‌پرد",
  "sorun.priz-yanik": "پریز بوی سوختگی می‌دهد",
  "sorun.elektrik-yok": "برق خانه قطع است",
  "sorun.kapida-kaldim": "پشت در مانده‌ام",
  "sorun.kilit-degisimi": "تعویض قفل",
  "sorun.anahtar-kirildi": "کلید داخل قفل شکسته",
  "sorun.sicak-su-yok": "آب گرم نداریم",
  "sorun.basinc-dusuk": "فشار پکیج افت می‌کند",
  "sorun.petek-isinmiyor": "شوفاژها گرم نمی‌شوند",
  "sorun.camasir-makinesi": "ماشین لباسشویی آب را تخلیه نمی‌کند",
  "sorun.buzdolabi": "یخچال خنک نمی‌کند",
  "sorun.bulasik-makinesi": "ماشین ظرفشویی کار نمی‌کند",

  "aciliyet.hemen": "همین الان",
  "aciliyet.bugun": "امروز",
  "aciliyet.randevu": "نوبت بعدی",

  "liste.baslik": "استادکاران نزدیک شما",
  "liste.arama": "جستجوی نام، تخصص یا محله",
  "liste.tumu": "همه",
  "liste.sadeceMusait": "فقط در دسترس",
  "liste.sonuc": "{n} استادکار",
  "liste.bos": "استادکاری مطابق جستجوی شما پیدا نشد.",

  "kart.musait": "الان در دسترس",
  "kart.mesgul": "مشغول",
  "kart.km": "{n} کیلومتر",
  "kart.yorum": "{n} نظر",
  "kart.cikis": "هزینه ایاب و ذهاب {tutar}",

  "detay.deneyim": "سابقه",
  "detay.yil": "{n} سال",
  "detay.tamamlanan": "کارهای انجام‌شده",
  "detay.bolge": "منطقه",
  "detay.sorunSec": "مشکل شما چیست؟",
  "detay.aciliyet": "کی بیاید؟",
  "detay.saat": "ساعت بازدید",
  "detay.tarih": "تاریخ",
  "detay.hemenNot": "استادکار حدود ۳۰ دقیقه دیگر دم در شماست.",
  "detay.acilUcret": "+{tutar} هزینه فوری",
  "detay.bugunSaatYok": "برای امروز وقت خالی نمانده، لطفاً نوبت بعدی را انتخاب کنید.",
  "detay.adres": "یادداشت آدرس",
  "detay.adresOrnek": "طبقه، شماره واحد، نام روی زنگ…",
  "detay.ustayaIletilen": "به زبان ترکی برای استادکار ارسال می‌شود:",
  "detay.mesgulUyari": "این استادکار الان مشغول است؛ فقط می‌توانید نوبت بگیرید.",
  "detay.cagir": "درخواست استادکار · {tutar}",
  "detay.cagirKisa": "درخواست استادکار",

  "cagri.baslik": "خلاصه درخواست",
  "cagri.bos": "هنوز درخواستی ثبت نکرده‌اید.",
  "cagri.ustaSec": "← یک استادکار انتخاب کنید",
  "cagri.usta": "استادکار",
  "cagri.sorun": "مشکل",
  "cagri.zaman": "زمان",
  "cagri.adres": "یادداشت آدرس",
  "cagri.cikis": "هزینه ایاب و ذهاب",
  "cagri.acil": "هزینه فوری",
  "cagri.toplam": "جمع تقریبی",
  "cagri.gece": "هزینه اضافه شبانه (22:00–08:00)",
  "cagri.pazar": "هزینه اضافه یکشنبه",
  "cagri.iscilik": "دستمزد تقریبی",
  "cagri.rust": "این ریز هزینه در هسته Rust برنامه محاسبه می‌شود.",
  "cagri.not": "هزینه قطعات و دستمزد را استادکار در محل تعیین می‌کند.",
  "cagri.onayla": "تأیید درخواست",
  "cagri.isleniyor": "در حال ساخت کد سفارش…",
  "cagri.vazgec": "انصراف",
  "cagri.hata": "ساخت کد ممکن نشد:",

  "is.baslik": "سفارش‌های من",
  "is.bos": "هنوز سفارشی ندارید.",
  "is.kod": "کد سفارش",
  "is.kodNot": "از استادکار بخواهید این کد را دم در بگوید.",
  "is.tamamla": "انجام شد",
  "is.iptal": "لغو",
  "is.dogrulaBaslik": "استادکار پشت در را تأیید کنید",
  "is.dogrulaYer": "کدی که استادکار می‌گوید",
  "is.dogrulaBtn": "بررسی",
  "is.dogru": "کد درست است — این همان استادکاری است که درخواست داده‌اید.",
  "is.yanlis": "این کد در سفارش‌های شما نیست. در را باز نکنید!",
  "is.formatHatali": "قالب کد نادرست است (مثال: UST-ELK-1210-K7QM).",
  "is.kontrolHatali": "شاید کد اشتباه وارد شده: نویسه کنترلی مطابقت ندارد. از استادکار بخواهید دوباره بگوید.",

  "durum.bekliyor": "در انتظار",
  "durum.yolda": "استادکار در راه است",
  "durum.tamamlandi": "انجام شد",
  "durum.iptal": "لغو شد",

  "profil.baslik": "پروفایل",
  "profil.misafir": "کاربر مهمان",
  "profil.isSayisi": "{n} سفارش دارید",
  "profil.ad": "نام و نام خانوادگی",
  "profil.telefon": "تلفن",
  "profil.adres": "آدرس",
  "profil.kaydet": "ذخیره",
  "profil.kaydedildi": "ذخیره شد ✓",
  "profil.ayarlar": "تنظیمات",
  "profil.dil": "زبان برنامه",
  "profil.tema": "پوسته",
  "profil.bilgi": "اطلاعات و قوانین",

  "sayfa.hakkinda": "درباره ما",
  "sayfa.iletisim": "تماس با ما",
  "sayfa.kosullar": "شرایط استفاده",
  "sayfa.gizlilik": "سیاست حریم خصوصی",

  "iletisim.aciklama": "برای سؤال، پیشنهاد یا پیوستن به‌عنوان استادکار به ما پیام دهید. معمولاً ظرف ۱ روز کاری پاسخ می‌دهیم.",
  "iletisim.ad": "نام شما",
  "iletisim.eposta": "ایمیل",
  "iletisim.konu": "موضوع",
  "iletisim.mesaj": "پیام شما",
  "iletisim.ipucu": "همه فیلدها را پر کنید؛ پیام باید دست‌کم ۱۰ کاراکتر باشد.",
  "iletisim.gonder": "ارسال",
  "iletisim.gonderiliyor": "در حال ارسال…",
  "iletisim.basarili": "پیام شما ارسال شد. سپاسگزاریم!",
  "konu.genel": "سؤال عمومی",
  "konu.usta": "می‌خواهم به‌عنوان استادکار بپیوندم",
  "konu.sikayet": "شکایت",
  "konu.oneri": "پیشنهاد",

  "liste.merhaba": "سلام",
  "liste.merhabaAd": "سلام، {ad}",
  "liste.soru": "چه چیزی را تعمیر کنیم؟",
  "liste.konumSec": "محله خود را انتخاب کنید",
  "liste.acilBaslik": "فوری است؟ نزدیک‌ترین استادکار در دسترس",
  "liste.acilYok": "الان استادکاری در دسترس نیست",
  "liste.aktifYolda": "{usta} در راه است · حدود {dk} دقیقه",
  "liste.aktifRandevu": "{usta} · نوبت {zaman}",
  "liste.favoriler": "علاقه‌مندی‌ها",
  "liste.dilimiKonusan": "فارسی صحبت می‌کند",
  "liste.sirala": "مرتب‌سازی",
  "liste.gorunum": "نمایش",
  "liste.liste": "فهرست",
  "liste.harita": "نقشه",
  "liste.filtreTemizle": "پاک کردن فیلترها",
  "sirala.onerilen": "پیشنهادی",
  "sirala.yakin": "نزدیک‌ترین",
  "sirala.puan": "بالاترین امتیاز",
  "sirala.fiyat": "ارزان‌ترین",

  "kart.kapali": "بسته · ساعت {saat} باز می‌شود",
  "kart.dk": "~{dk} دقیقه",
  "kart.favoriEkle": "افزودن به علاقه‌مندی‌ها",
  "kart.favoriCikar": "حذف از علاقه‌مندی‌ها",
  "kart.favoriEklendi": "{ad} به علاقه‌مندی‌ها اضافه شد",
  "kart.favoriCikarildi": "{ad} از علاقه‌مندی‌ها حذف شد",

  "rozet.dogrulanmis": "هویت تأییدشده",
  "rozet.sigortali": "کار بیمه‌شده",
  "rozet.7-24": "خدمات شبانه‌روزی",
  "rozet.hizli-yanit": "پاسخ سریع",

  "detay.geri": "بازگشت",
  "detay.yanit": "زمان پاسخ",
  "detay.mesafe": "فاصله",
  "detay.calisma": "ساعات کاری",
  "detay.724": "۲۴ ساعته، ۷ روز هفته",
  "detay.diller": "زبان‌هایی که صحبت می‌کند",
  "detay.dilinizi": "به زبان شما صحبت می‌کند",
  "detay.sure": "کار حدود {dk} دقیقه",
  "detay.guvenlik": "تا رسیدن استادکار",
  "detay.foto": "عکس خرابی را اضافه کنید (اختیاری)",
  "detay.fotoNot": "عکس به استادکار کمک می‌کند قطعه درست را بیاورد.",
  "detay.fotoKaldir": "حذف عکس",
  "detay.yorumlar": "نظرها",
  "detay.yorumSayisi": "{n} امتیاز",
  "detay.tumYorumlar": "نمایش همه نظرها",
  "detay.sizinYorumunuz": "نظر شما",
  "detay.kapaliUyari": "این استادکار الان بسته است (ساعت {saat} باز می‌شود)؛ می‌توانید ساعتی دیرتر در امروز یا نوبت بعدی را انتخاب کنید.",
  "detay.bulunamadi": "استادکار پیدا نشد.",

  "ipucu.su-sizintisi": "شیر اصلی آب را ببندید و آب نشتی را از پریزها و وسایل برقی دور نگه دارید.",
  "ipucu.tikali-gider": "مواد شیمیایی لوله‌بازکن نریزید و تا آمدن استادکار از آن فاضلاب استفاده نکنید.",
  "ipucu.musluk-ariza": "شیر فرعی زیر روشویی را ببندید.",
  "ipucu.sigorta-atiyor": "آخرین وسیله‌ای را که وصل کرده‌اید از برق بکشید و فیوز را پشت سر هم بالا نزنید.",
  "ipucu.priz-yanik": "فیوز آن خط را قطع کنید و به پریز دست نزنید. اگر دود یا آتش هست با ۱۱۲ تماس بگیرید.",
  "ipucu.elektrik-yok": "اگر برق همسایه‌ها هم قطع است شاید قطعی عمومی باشد؛ در یخچال را باز نکنید.",
  "ipucu.kapida-kaldim": "در را به زور باز نکنید؛ کارت شناسایی همراهتان باشد، استادکار مدرک سکونت می‌خواهد.",
  "ipucu.kilit-degisimi": "عکس قفل خود را اضافه کنید تا استادکار سیلندر مناسب را بیاورد.",
  "ipucu.anahtar-kirildi": "خودتان تکه شکسته را بیرون نکشید؛ ممکن است قفل بیشتر آسیب ببیند.",
  "ipucu.sicak-su-yok": "کد خطای روی صفحه پکیج را یادداشت کنید و یک بار آن را خاموش و روشن کنید.",
  "ipucu.basinc-dusuk": "از نشانگر فشار عکس بگیرید و پکیج را خاموش کنید.",
  "ipucu.petek-isinmiyor": "مطمئن شوید شیرهای شوفاژها باز هستند.",
  "ipucu.camasir-makinesi": "ماشین را خاموش و از برق جدا کنید؛ در آن را به زور باز نکنید.",
  "ipucu.buzdolabi": "تا جای ممکن در یخچال را بسته نگه دارید و مواد فاسدشدنی را به جای خنک ببرید.",
  "ipucu.bulasik-makinesi": "دوشاخه دستگاه را بکشید و شیر آب آن را ببندید.",

  "harita.etiket": "نقشه استادکاران در استانبول",
  "harita.sen": "شما",
  "harita.profil": "دیدن پروفایل",
  "harita.avrupa": "بخش اروپایی",
  "harita.asya": "بخش آسیایی",

  "karsilama.baslik": "به Ustam خوش آمدید",
  "karsilama.alt": "برای هر خرابی در خانه، نزدیک‌ترین استادکار در دسترس را به زبان خودتان خبر کنید.",
  "karsilama.dilSec": "زبان خود را انتخاب کنید",
  "karsilama.semtSec": "در کدام محله هستید؟",
  "karsilama.semtNot": "برای نشان دادن نزدیک‌ترین استادکاران استفاده می‌شود و از دستگاه شما خارج نمی‌شود.",
  "karsilama.devam": "ادامه",
  "karsilama.basla": "شروع",
  "karsilama.ozellik1": "استادکاران در دسترس نزدیک شما و زمان رسیدن",
  "karsilama.ozellik2": "مشکل خود را به زبان خودتان بگویید",
  "karsilama.ozellik3": "تأیید امن دم در با کد سفارش",
};

export const sozlukler: Record<Dil, Record<Anahtar, string>> = { tr, en, ar, fa };
