// Arayüz metinleri — 4 dil (TR · EN · AR · FA). AR ve FA sağdan sola (RTL) gösterilir.
// Türkçe sözlük kaynak kabul edilir; diğer diller aynı anahtarların tamamını içermek zorundadır.
import type { Dil } from "../types/ustam";

const tr = {
  "uygulama.slogan": "Arıza senden, usta bizden.",

  "nav.ustalar": "Ustalar",
  "nav.cagri": "Çağrı",
  "nav.isEmirleri": "İş Emirlerim",
  "nav.profil": "Profil",

  "tema.gunduzeGec": "Gündüz moduna geç",
  "tema.geceyeGec": "Gece moduna geç",
  "dil.sec": "Dil seçin",

  "kategori.tesisat": "Tesisat",
  "kategori.elektrik": "Elektrik",
  "kategori.cilingir": "Çilingir",
  "kategori.kombi": "Kombi",
  "kategori.beyaz-esya": "Beyaz Eşya",

  "sorun.su-sizintisi": "Su sızıntısı",
  "sorun.tikali-gider": "Tıkalı gider",
  "sorun.musluk-ariza": "Musluk arızası",
  "sorun.sigorta-atiyor": "Sigorta sürekli atıyor",
  "sorun.priz-yanik": "Priz yanık kokuyor",
  "sorun.elektrik-yok": "Evde elektrik yok",
  "sorun.kapida-kaldim": "Kapıda kaldım",
  "sorun.kilit-degisimi": "Kilit değişimi",
  "sorun.anahtar-kirildi": "Anahtar kilitte kırıldı",
  "sorun.sicak-su-yok": "Sıcak su yok",
  "sorun.basinc-dusuk": "Kombi basınç düşürüyor",
  "sorun.petek-isinmiyor": "Petekler ısınmıyor",
  "sorun.camasir-makinesi": "Çamaşır makinesi su boşaltmıyor",
  "sorun.buzdolabi": "Buzdolabı soğutmuyor",
  "sorun.bulasik-makinesi": "Bulaşık makinesi çalışmıyor",

  "aciliyet.hemen": "Hemen",
  "aciliyet.bugun": "Bugün",
  "aciliyet.randevu": "Randevu",

  "liste.baslik": "Yakınındaki ustalar",
  "liste.arama": "Usta adı, uzmanlık veya semt ara",
  "liste.tumu": "Tümü",
  "liste.sadeceMusait": "Sadece müsait olanlar",
  "liste.sonuc": "{n} usta",
  "liste.bos": "Aramanıza uygun usta bulunamadı.",

  "kart.musait": "Şu an müsait",
  "kart.mesgul": "Meşgul",
  "kart.km": "{n} km",
  "kart.yorum": "{n} yorum",
  "kart.cikis": "Çıkış ücreti {tutar}",

  "detay.deneyim": "Deneyim",
  "detay.yil": "{n} yıl",
  "detay.tamamlanan": "Tamamlanan iş",
  "detay.bolge": "Bölge",
  "detay.sorunSec": "Sorununuz ne?",
  "detay.aciliyet": "Ne zaman gelsin?",
  "detay.saat": "Ziyaret saati",
  "detay.tarih": "Tarih",
  "detay.hemenNot": "Usta yaklaşık 30 dakika içinde kapınızda.",
  "detay.acilUcret": "+{tutar} acil servis ücreti",
  "detay.bugunSaatYok": "Bugün için boş saat kalmadı, lütfen randevu seçin.",
  "detay.adres": "Adres notu",
  "detay.adresOrnek": "Kat, daire no, zil adı…",
  "detay.ustayaIletilen": "Ustaya Türkçe iletilecek:",
  "detay.mesgulUyari": "Bu usta şu an meşgul; yalnızca randevu alabilirsiniz.",
  "detay.cagir": "Ustayı çağır · {tutar}",

  "cagri.baslik": "Çağrı özeti",
  "cagri.bos": "Henüz bir çağrı oluşturmadınız.",
  "cagri.ustaSec": "Bir usta seçin →",
  "cagri.usta": "Usta",
  "cagri.sorun": "Sorun",
  "cagri.zaman": "Zaman",
  "cagri.adres": "Adres notu",
  "cagri.cikis": "Çıkış ücreti",
  "cagri.acil": "Acil servis ücreti",
  "cagri.toplam": "Tahmini toplam",
  "cagri.not": "Parça ve işçilik ücreti usta tarafından yerinde belirlenir.",
  "cagri.onayla": "Çağrıyı onayla",
  "cagri.isleniyor": "İş emri kodu üretiliyor…",
  "cagri.vazgec": "Vazgeç",
  "cagri.hata": "Kod üretilemedi:",

  "is.baslik": "İş Emirlerim",
  "is.bos": "Henüz iş emriniz yok.",
  "is.kod": "İş emri kodu",
  "is.kodNot": "Usta kapıya geldiğinde bu kodu söylemesini isteyin.",
  "is.tamamla": "Tamamlandı",
  "is.iptal": "İptal et",
  "is.dogrulaBaslik": "Kapıdaki ustayı doğrula",
  "is.dogrulaYer": "Ustanın söylediği kod",
  "is.dogrulaBtn": "Doğrula",
  "is.dogru": "Kod doğru — bu, sizin çağırdığınız usta.",
  "is.yanlis": "Bu kod iş emirlerinizde yok. Kapıyı açmayın!",
  "is.formatHatali": "Kod biçimi hatalı (ör. UST-ELK-1210-K7Q4).",

  "durum.bekliyor": "Bekliyor",
  "durum.yolda": "Usta yolda",
  "durum.tamamlandi": "Tamamlandı",
  "durum.iptal": "İptal edildi",

  "profil.baslik": "Profil",
  "profil.misafir": "Misafir kullanıcı",
  "profil.isSayisi": "{n} iş emriniz var",
  "profil.ad": "Ad Soyad",
  "profil.telefon": "Telefon",
  "profil.adres": "Adres",
  "profil.kaydet": "Kaydet",
  "profil.kaydedildi": "Kaydedildi ✓",
  "profil.ayarlar": "Ayarlar",
  "profil.dil": "Uygulama dili",
  "profil.tema": "Gece modu",
  "profil.bilgi": "Bilgi ve yasal",

  "sayfa.hakkinda": "Hakkında",
  "sayfa.iletisim": "İletişim",
  "sayfa.kosullar": "Kullanım Koşulları",
  "sayfa.gizlilik": "Gizlilik Politikası",

  "iletisim.aciklama": "Soru, öneri veya usta başvurusu için bize yazın. Genellikle 1 iş günü içinde yanıt veririz.",
  "iletisim.ad": "Adınız",
  "iletisim.eposta": "E-posta",
  "iletisim.konu": "Konu",
  "iletisim.mesaj": "Mesajınız",
  "iletisim.ipucu": "Tüm alanları doldurun; mesaj en az 10 karakter olmalı.",
  "iletisim.gonder": "Gönder",
  "iletisim.gonderiliyor": "Gönderiliyor…",
  "iletisim.basarili": "Mesajınız iletildi. Teşekkür ederiz!",
  "konu.genel": "Genel soru",
  "konu.usta": "Usta olarak katılmak istiyorum",
  "konu.sikayet": "Şikayet",
  "konu.oneri": "Öneri",
} as const;

export type Anahtar = keyof typeof tr;

const en: Record<Anahtar, string> = {
  "uygulama.slogan": "Your breakdown, our pro.",

  "nav.ustalar": "Pros",
  "nav.cagri": "Request",
  "nav.isEmirleri": "My Jobs",
  "nav.profil": "Profile",

  "tema.gunduzeGec": "Switch to light mode",
  "tema.geceyeGec": "Switch to dark mode",
  "dil.sec": "Choose language",

  "kategori.tesisat": "Plumbing",
  "kategori.elektrik": "Electrical",
  "kategori.cilingir": "Locksmith",
  "kategori.kombi": "Boiler",
  "kategori.beyaz-esya": "Appliances",

  "sorun.su-sizintisi": "Water leak",
  "sorun.tikali-gider": "Clogged drain",
  "sorun.musluk-ariza": "Broken faucet",
  "sorun.sigorta-atiyor": "Fuse keeps tripping",
  "sorun.priz-yanik": "Outlet smells burnt",
  "sorun.elektrik-yok": "No power at home",
  "sorun.kapida-kaldim": "Locked out",
  "sorun.kilit-degisimi": "Lock replacement",
  "sorun.anahtar-kirildi": "Key broke in the lock",
  "sorun.sicak-su-yok": "No hot water",
  "sorun.basinc-dusuk": "Boiler losing pressure",
  "sorun.petek-isinmiyor": "Radiators not heating",
  "sorun.camasir-makinesi": "Washing machine won't drain",
  "sorun.buzdolabi": "Fridge not cooling",
  "sorun.bulasik-makinesi": "Dishwasher not working",

  "aciliyet.hemen": "Right now",
  "aciliyet.bugun": "Today",
  "aciliyet.randevu": "Schedule",

  "liste.baslik": "Pros near you",
  "liste.arama": "Search name, trade or district",
  "liste.tumu": "All",
  "liste.sadeceMusait": "Available only",
  "liste.sonuc": "{n} pros",
  "liste.bos": "No pros match your search.",

  "kart.musait": "Available now",
  "kart.mesgul": "Busy",
  "kart.km": "{n} km",
  "kart.yorum": "{n} reviews",
  "kart.cikis": "Call-out fee {tutar}",

  "detay.deneyim": "Experience",
  "detay.yil": "{n} yrs",
  "detay.tamamlanan": "Jobs done",
  "detay.bolge": "Area",
  "detay.sorunSec": "What's the problem?",
  "detay.aciliyet": "When should they come?",
  "detay.saat": "Visit time",
  "detay.tarih": "Date",
  "detay.hemenNot": "The pro will be at your door in about 30 minutes.",
  "detay.acilUcret": "+{tutar} emergency fee",
  "detay.bugunSaatYok": "No slots left today, please schedule a visit.",
  "detay.adres": "Address note",
  "detay.adresOrnek": "Floor, flat no, doorbell name…",
  "detay.ustayaIletilen": "Sent to the pro in Turkish:",
  "detay.mesgulUyari": "This pro is busy right now; you can only schedule a visit.",
  "detay.cagir": "Call the pro · {tutar}",

  "cagri.baslik": "Request summary",
  "cagri.bos": "You haven't created a request yet.",
  "cagri.ustaSec": "Choose a pro →",
  "cagri.usta": "Pro",
  "cagri.sorun": "Problem",
  "cagri.zaman": "Time",
  "cagri.adres": "Address note",
  "cagri.cikis": "Call-out fee",
  "cagri.acil": "Emergency fee",
  "cagri.toplam": "Estimated total",
  "cagri.not": "Parts and labour are priced on site by the pro.",
  "cagri.onayla": "Confirm request",
  "cagri.isleniyor": "Generating job code…",
  "cagri.vazgec": "Cancel",
  "cagri.hata": "Could not generate code:",

  "is.baslik": "My Jobs",
  "is.bos": "You have no jobs yet.",
  "is.kod": "Job code",
  "is.kodNot": "Ask the pro to tell you this code at the door.",
  "is.tamamla": "Mark done",
  "is.iptal": "Cancel",
  "is.dogrulaBaslik": "Verify the pro at your door",
  "is.dogrulaYer": "Code the pro tells you",
  "is.dogrulaBtn": "Verify",
  "is.dogru": "Code is correct — this is the pro you called.",
  "is.yanlis": "This code is not in your jobs. Do not open the door!",
  "is.formatHatali": "Invalid code format (e.g. UST-ELK-1210-K7Q4).",

  "durum.bekliyor": "Scheduled",
  "durum.yolda": "On the way",
  "durum.tamamlandi": "Done",
  "durum.iptal": "Cancelled",

  "profil.baslik": "Profile",
  "profil.misafir": "Guest user",
  "profil.isSayisi": "You have {n} jobs",
  "profil.ad": "Full name",
  "profil.telefon": "Phone",
  "profil.adres": "Address",
  "profil.kaydet": "Save",
  "profil.kaydedildi": "Saved ✓",
  "profil.ayarlar": "Settings",
  "profil.dil": "App language",
  "profil.tema": "Dark mode",
  "profil.bilgi": "Info & legal",

  "sayfa.hakkinda": "About",
  "sayfa.iletisim": "Contact",
  "sayfa.kosullar": "Terms of Use",
  "sayfa.gizlilik": "Privacy Policy",

  "iletisim.aciklama": "Write to us with questions, ideas or to join as a pro. We usually reply within 1 business day.",
  "iletisim.ad": "Your name",
  "iletisim.eposta": "Email",
  "iletisim.konu": "Subject",
  "iletisim.mesaj": "Your message",
  "iletisim.ipucu": "Fill in all fields; the message must be at least 10 characters.",
  "iletisim.gonder": "Send",
  "iletisim.gonderiliyor": "Sending…",
  "iletisim.basarili": "Your message has been sent. Thank you!",
  "konu.genel": "General question",
  "konu.usta": "I want to join as a pro",
  "konu.sikayet": "Complaint",
  "konu.oneri": "Suggestion",
};

const ar: Record<Anahtar, string> = {
  "uygulama.slogan": "العطل عليك، والفنّي علينا.",

  "nav.ustalar": "الفنّيون",
  "nav.cagri": "الطلب",
  "nav.isEmirleri": "طلباتي",
  "nav.profil": "حسابي",

  "tema.gunduzeGec": "التبديل إلى الوضع الفاتح",
  "tema.geceyeGec": "التبديل إلى الوضع الداكن",
  "dil.sec": "اختر اللغة",

  "kategori.tesisat": "سباكة",
  "kategori.elektrik": "كهرباء",
  "kategori.cilingir": "أقفال ومفاتيح",
  "kategori.kombi": "غلاية التدفئة",
  "kategori.beyaz-esya": "أجهزة منزلية",

  "sorun.su-sizintisi": "تسرّب مياه",
  "sorun.tikali-gider": "انسداد المصرف",
  "sorun.musluk-ariza": "عطل في الحنفية",
  "sorun.sigorta-atiyor": "القاطع الكهربائي يفصل باستمرار",
  "sorun.priz-yanik": "رائحة احتراق من المقبس",
  "sorun.elektrik-yok": "لا توجد كهرباء في المنزل",
  "sorun.kapida-kaldim": "أنا عالق خارج الباب",
  "sorun.kilit-degisimi": "تغيير القفل",
  "sorun.anahtar-kirildi": "انكسر المفتاح داخل القفل",
  "sorun.sicak-su-yok": "لا يوجد ماء ساخن",
  "sorun.basinc-dusuk": "ضغط الغلاية ينخفض",
  "sorun.petek-isinmiyor": "المشعات لا تسخن",
  "sorun.camasir-makinesi": "الغسالة لا تصرّف الماء",
  "sorun.buzdolabi": "الثلاجة لا تبرّد",
  "sorun.bulasik-makinesi": "غسالة الصحون لا تعمل",

  "aciliyet.hemen": "فورًا",
  "aciliyet.bugun": "اليوم",
  "aciliyet.randevu": "موعد لاحق",

  "liste.baslik": "فنّيون بالقرب منك",
  "liste.arama": "ابحث بالاسم أو الاختصاص أو الحي",
  "liste.tumu": "الكل",
  "liste.sadeceMusait": "المتاحون فقط",
  "liste.sonuc": "{n} فنّي",
  "liste.bos": "لا يوجد فنّي يطابق بحثك.",

  "kart.musait": "متاح الآن",
  "kart.mesgul": "مشغول",
  "kart.km": "{n} كم",
  "kart.yorum": "{n} تقييم",
  "kart.cikis": "رسوم الزيارة {tutar}",

  "detay.deneyim": "الخبرة",
  "detay.yil": "{n} سنة",
  "detay.tamamlanan": "أعمال منجزة",
  "detay.bolge": "المنطقة",
  "detay.sorunSec": "ما هي المشكلة؟",
  "detay.aciliyet": "متى يأتي الفنّي؟",
  "detay.saat": "وقت الزيارة",
  "detay.tarih": "التاريخ",
  "detay.hemenNot": "سيصل الفنّي إلى بابك خلال 30 دقيقة تقريبًا.",
  "detay.acilUcret": "+{tutar} رسوم الطوارئ",
  "detay.bugunSaatYok": "لا توجد مواعيد متبقية اليوم، يرجى اختيار موعد لاحق.",
  "detay.adres": "ملاحظة العنوان",
  "detay.adresOrnek": "الطابق، رقم الشقة، اسم الجرس…",
  "detay.ustayaIletilen": "سيُرسل إلى الفنّي بالتركية:",
  "detay.mesgulUyari": "هذا الفنّي مشغول الآن؛ يمكنك حجز موعد لاحق فقط.",
  "detay.cagir": "اطلب الفنّي · {tutar}",

  "cagri.baslik": "ملخّص الطلب",
  "cagri.bos": "لم تُنشئ أي طلب بعد.",
  "cagri.ustaSec": "← اختر فنّيًا",
  "cagri.usta": "الفنّي",
  "cagri.sorun": "المشكلة",
  "cagri.zaman": "الوقت",
  "cagri.adres": "ملاحظة العنوان",
  "cagri.cikis": "رسوم الزيارة",
  "cagri.acil": "رسوم الطوارئ",
  "cagri.toplam": "الإجمالي التقديري",
  "cagri.not": "يحدّد الفنّي تكلفة القطع والعمل في الموقع.",
  "cagri.onayla": "تأكيد الطلب",
  "cagri.isleniyor": "جارٍ إنشاء رمز الطلب…",
  "cagri.vazgec": "إلغاء",
  "cagri.hata": "تعذّر إنشاء الرمز:",

  "is.baslik": "طلباتي",
  "is.bos": "لا توجد لديك طلبات بعد.",
  "is.kod": "رمز الطلب",
  "is.kodNot": "اطلب من الفنّي أن يذكر هذا الرمز عند الباب.",
  "is.tamamla": "تمّ الإنجاز",
  "is.iptal": "إلغاء",
  "is.dogrulaBaslik": "تحقّق من الفنّي عند الباب",
  "is.dogrulaYer": "الرمز الذي يذكره الفنّي",
  "is.dogrulaBtn": "تحقّق",
  "is.dogru": "الرمز صحيح — هذا هو الفنّي الذي طلبته.",
  "is.yanlis": "هذا الرمز غير موجود في طلباتك. لا تفتح الباب!",
  "is.formatHatali": "صيغة الرمز غير صحيحة (مثال: UST-ELK-1210-K7Q4).",

  "durum.bekliyor": "بانتظار الموعد",
  "durum.yolda": "الفنّي في الطريق",
  "durum.tamamlandi": "منجز",
  "durum.iptal": "ملغى",

  "profil.baslik": "حسابي",
  "profil.misafir": "مستخدم زائر",
  "profil.isSayisi": "لديك {n} طلبات",
  "profil.ad": "الاسم الكامل",
  "profil.telefon": "الهاتف",
  "profil.adres": "العنوان",
  "profil.kaydet": "حفظ",
  "profil.kaydedildi": "تمّ الحفظ ✓",
  "profil.ayarlar": "الإعدادات",
  "profil.dil": "لغة التطبيق",
  "profil.tema": "الوضع الداكن",
  "profil.bilgi": "معلومات وشروط",

  "sayfa.hakkinda": "حول التطبيق",
  "sayfa.iletisim": "اتصل بنا",
  "sayfa.kosullar": "شروط الاستخدام",
  "sayfa.gizlilik": "سياسة الخصوصية",

  "iletisim.aciklama": "راسلنا لأي سؤال أو اقتراح أو للانضمام كفنّي. نرد عادةً خلال يوم عمل واحد.",
  "iletisim.ad": "اسمك",
  "iletisim.eposta": "البريد الإلكتروني",
  "iletisim.konu": "الموضوع",
  "iletisim.mesaj": "رسالتك",
  "iletisim.ipucu": "املأ جميع الحقول؛ يجب ألا تقل الرسالة عن 10 أحرف.",
  "iletisim.gonder": "إرسال",
  "iletisim.gonderiliyor": "جارٍ الإرسال…",
  "iletisim.basarili": "تم إرسال رسالتك. شكرًا لك!",
  "konu.genel": "سؤال عام",
  "konu.usta": "أريد الانضمام كفنّي",
  "konu.sikayet": "شكوى",
  "konu.oneri": "اقتراح",
};

const fa: Record<Anahtar, string> = {
  "uygulama.slogan": "خرابی با شما، استادکار با ما.",

  "nav.ustalar": "استادکاران",
  "nav.cagri": "درخواست",
  "nav.isEmirleri": "سفارش‌های من",
  "nav.profil": "پروفایل",

  "tema.gunduzeGec": "رفتن به حالت روشن",
  "tema.geceyeGec": "رفتن به حالت تاریک",
  "dil.sec": "انتخاب زبان",

  "kategori.tesisat": "لوله‌کشی",
  "kategori.elektrik": "برق‌کاری",
  "kategori.cilingir": "کلیدسازی",
  "kategori.kombi": "پکیج",
  "kategori.beyaz-esya": "لوازم خانگی",

  "sorun.su-sizintisi": "نشت آب",
  "sorun.tikali-gider": "گرفتگی فاضلاب",
  "sorun.musluk-ariza": "خرابی شیر آب",
  "sorun.sigorta-atiyor": "فیوز مدام می‌پرد",
  "sorun.priz-yanik": "پریز بوی سوختگی می‌دهد",
  "sorun.elektrik-yok": "برق خانه قطع است",
  "sorun.kapida-kaldim": "پشت در مانده‌ام",
  "sorun.kilit-degisimi": "تعویض قفل",
  "sorun.anahtar-kirildi": "کلید داخل قفل شکسته",
  "sorun.sicak-su-yok": "آب گرم نداریم",
  "sorun.basinc-dusuk": "فشار پکیج افت می‌کند",
  "sorun.petek-isinmiyor": "شوفاژها گرم نمی‌شوند",
  "sorun.camasir-makinesi": "ماشین لباسشویی آب را تخلیه نمی‌کند",
  "sorun.buzdolabi": "یخچال خنک نمی‌کند",
  "sorun.bulasik-makinesi": "ماشین ظرفشویی کار نمی‌کند",

  "aciliyet.hemen": "همین الان",
  "aciliyet.bugun": "امروز",
  "aciliyet.randevu": "نوبت بعدی",

  "liste.baslik": "استادکاران نزدیک شما",
  "liste.arama": "جستجوی نام، تخصص یا محله",
  "liste.tumu": "همه",
  "liste.sadeceMusait": "فقط در دسترس",
  "liste.sonuc": "{n} استادکار",
  "liste.bos": "استادکاری مطابق جستجوی شما پیدا نشد.",

  "kart.musait": "الان در دسترس",
  "kart.mesgul": "مشغول",
  "kart.km": "{n} کیلومتر",
  "kart.yorum": "{n} نظر",
  "kart.cikis": "هزینه ایاب و ذهاب {tutar}",

  "detay.deneyim": "سابقه",
  "detay.yil": "{n} سال",
  "detay.tamamlanan": "کارهای انجام‌شده",
  "detay.bolge": "منطقه",
  "detay.sorunSec": "مشکل شما چیست؟",
  "detay.aciliyet": "کی بیاید؟",
  "detay.saat": "ساعت بازدید",
  "detay.tarih": "تاریخ",
  "detay.hemenNot": "استادکار حدود ۳۰ دقیقه دیگر دم در شماست.",
  "detay.acilUcret": "+{tutar} هزینه فوری",
  "detay.bugunSaatYok": "برای امروز وقت خالی نمانده، لطفاً نوبت بعدی را انتخاب کنید.",
  "detay.adres": "یادداشت آدرس",
  "detay.adresOrnek": "طبقه، شماره واحد، نام روی زنگ…",
  "detay.ustayaIletilen": "به زبان ترکی برای استادکار ارسال می‌شود:",
  "detay.mesgulUyari": "این استادکار الان مشغول است؛ فقط می‌توانید نوبت بگیرید.",
  "detay.cagir": "درخواست استادکار · {tutar}",

  "cagri.baslik": "خلاصه درخواست",
  "cagri.bos": "هنوز درخواستی ثبت نکرده‌اید.",
  "cagri.ustaSec": "← یک استادکار انتخاب کنید",
  "cagri.usta": "استادکار",
  "cagri.sorun": "مشکل",
  "cagri.zaman": "زمان",
  "cagri.adres": "یادداشت آدرس",
  "cagri.cikis": "هزینه ایاب و ذهاب",
  "cagri.acil": "هزینه فوری",
  "cagri.toplam": "جمع تقریبی",
  "cagri.not": "هزینه قطعات و دستمزد را استادکار در محل تعیین می‌کند.",
  "cagri.onayla": "تأیید درخواست",
  "cagri.isleniyor": "در حال ساخت کد سفارش…",
  "cagri.vazgec": "انصراف",
  "cagri.hata": "ساخت کد ممکن نشد:",

  "is.baslik": "سفارش‌های من",
  "is.bos": "هنوز سفارشی ندارید.",
  "is.kod": "کد سفارش",
  "is.kodNot": "از استادکار بخواهید این کد را دم در بگوید.",
  "is.tamamla": "انجام شد",
  "is.iptal": "لغو",
  "is.dogrulaBaslik": "استادکار پشت در را تأیید کنید",
  "is.dogrulaYer": "کدی که استادکار می‌گوید",
  "is.dogrulaBtn": "بررسی",
  "is.dogru": "کد درست است — این همان استادکاری است که درخواست داده‌اید.",
  "is.yanlis": "این کد در سفارش‌های شما نیست. در را باز نکنید!",
  "is.formatHatali": "قالب کد نادرست است (مثال: UST-ELK-1210-K7Q4).",

  "durum.bekliyor": "در انتظار",
  "durum.yolda": "استادکار در راه است",
  "durum.tamamlandi": "انجام شد",
  "durum.iptal": "لغو شد",

  "profil.baslik": "پروفایل",
  "profil.misafir": "کاربر مهمان",
  "profil.isSayisi": "{n} سفارش دارید",
  "profil.ad": "نام و نام خانوادگی",
  "profil.telefon": "تلفن",
  "profil.adres": "آدرس",
  "profil.kaydet": "ذخیره",
  "profil.kaydedildi": "ذخیره شد ✓",
  "profil.ayarlar": "تنظیمات",
  "profil.dil": "زبان برنامه",
  "profil.tema": "حالت تاریک",
  "profil.bilgi": "اطلاعات و قوانین",

  "sayfa.hakkinda": "درباره ما",
  "sayfa.iletisim": "تماس با ما",
  "sayfa.kosullar": "شرایط استفاده",
  "sayfa.gizlilik": "سیاست حریم خصوصی",

  "iletisim.aciklama": "برای سؤال، پیشنهاد یا پیوستن به‌عنوان استادکار به ما پیام دهید. معمولاً ظرف ۱ روز کاری پاسخ می‌دهیم.",
  "iletisim.ad": "نام شما",
  "iletisim.eposta": "ایمیل",
  "iletisim.konu": "موضوع",
  "iletisim.mesaj": "پیام شما",
  "iletisim.ipucu": "همه فیلدها را پر کنید؛ پیام باید دست‌کم ۱۰ کاراکتر باشد.",
  "iletisim.gonder": "ارسال",
  "iletisim.gonderiliyor": "در حال ارسال…",
  "iletisim.basarili": "پیام شما ارسال شد. سپاسگزاریم!",
  "konu.genel": "سؤال عمومی",
  "konu.usta": "می‌خواهم به‌عنوان استادکار بپیوندم",
  "konu.sikayet": "شکایت",
  "konu.oneri": "پیشنهاد",
};

export const sozlukler: Record<Dil, Record<Anahtar, string>> = { tr, en, ar, fa };
